authentik:
    postgresql:
        #ENC[AES256_GCM,data:JGvwx01wjKFH8EM+j9oQm2eRFcOrhZKTLruiruPa21gedoyBMIO0dKTlMzwYoU2hiIs2od13HvdFTnpFOQ==,iv:dTtip1QAQAXATZ0rh7/AkQm0DaLQIIpfYXUKfpAO0NM=,tag:hi93WoTYFaFCI7TI1njSeA==,type:comment]
        #ENC[AES256_GCM,data:Xn1JSjgDHtm5,iv:hl53h54GGjxfy76iQKXaI1r+yPdRbVTDCEu+fL9iJ5k=,tag:XEa6OSyQw1ywROQCZkE5Dg==,type:comment]
        #ENC[AES256_GCM,data:HDwGgIx5U8a6oFo5bL+cgJqiRIhGwUDsjtZzT6bJfOuSsCw=,iv:nvyKd5yvQ1QLCENWGcEPMV8RzXyeO/WtLKXr9d0F56E=,tag:JHJp7cKGm0eaC7ScpY0yJQ==,type:comment]
        #ENC[AES256_GCM,data:tDucvcbNxkFP0F18I5cmJnJM+isbVllbEXeIVb2XnrCS0MWkysh1TnNaD9YaaoDl5COnZ5SevoYjbE38O0E=,iv:qk6c5xMu5IXgwtF2gOPaRliVqBM9i3IXvsZRRMfOAiE=,tag:43V1YREvrA2kt7Zfl+C2sw==,type:comment]
        user: ENC[AES256_GCM,data:uRkql4tn5myW,iv:aGXKzhVgeXfSPDcMGewgJhLUCr5PE+NBLE1xj5rmjCE=,tag:RVPdcZjcMgEkk7CxMI+D6w==,type:str]
        password: ENC[AES256_GCM,data:4CS5huaPuTm4TsnuX81NPk7b2g==,iv:8g8CFkDDIkgw9huMxQhevmkztY7Zb+NSU/HPBAYDM6E=,tag:h1J6hNkm9Yipp3YhTT2Ltg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQUFSSGdpenh3VXlGVHNs
            N0pmdzIyTzc3QTIvd29QS2FNbmtVSncxcGhVClpZNk9MaEFuOGJZNWJKR0phcnFp
            MzlDc2wwdlJ5M1B4V3hqVjZxbWJuTjQKLS0tIGx1REVlN2xFUHVpUG0wNGVtNnhq
            YUx0TGgvNXI0UStVK3B4cjBKTVpCajgKJ1FB25GwNOF9QENw8uB2PaXzuqQJPUyD
            FkeXODkxu6kLxmhSt8gU36va+BLv6V4vDafBQTcnyd0IHvxmTtN1wA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-07-05T00:31:59Z"
    mac: ENC[AES256_GCM,data:IUp2dlgl20nEKuK722ltAs3knfJyFqu/lRjnIKr6qu/m0j/Z3CVKYtSd80VxRoS/lsvm9fmNcl2rLuCNlyUMFj0JSuVoE5UPEoa9OXwmwSK8bvz3a2wDURFNODucLcYHB4NQTbu0YljXZWXI1qLJ/lnyLvR1pRPaCirTfeNbP9s=,iv:10+oSANcLnvlCVLM3mdaMWwRbYMXLeDMtfJ75/225fM=,tag:O07i44kOo/AXKYJ+9O5MPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
