config:
  filters:
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
      name: AdGuard DNS filter
      id: 1
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
      name: AdAway Default Blocklist
      id: 2
    - enabled: true
      url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
      name: Perflyst and Dandelion Sprout's Smart-TV Blocklist
      id: 1733088564
  http:
    address: 0.0.0.0:80
