#ENC[AES256_GCM,data:e8VdKV5oswkb3dzOpxOaR0friYKhFcZ46Fw2fHX21Q8rpN/L1yFqiW2+MwOwK6FzwN312s+mjVRfpRJ51Re03JOFuLUhEwVpjkLyoqp5ZOhPe6T2+Q==,iv:Jwik3InREpd1fjYK7L2gORCFm6Pt9q59zKKXIFjX7y0=,tag:bRRxgJbRsYaviC6tzWxJuQ==,type:comment]
mqtt:
    host: ENC[AES256_GCM,data:jYokGbE4Cs4fmquryxYJIzCNHg==,iv:fRwMjcPEpLtPuhi34noaRUE7rWTwudbdSs33Y7hZmcw=,tag:2zlWax0LwxSa3GFJtPiXzw==,type:str]
record:
    enabled: ENC[AES256_GCM,data:60WvbQ==,iv:5t796vZ+7ink7cIPAtUZMW9ihyCmV2qThbZxahIfqc4=,tag:RT+a+YdiB+9ogrX5+gsyfQ==,type:bool]
detectors:
    ov:
        type: ENC[AES256_GCM,data:2FqXsGjPOVE=,iv:zednBPA2Vi1lef8t8d/r2hHijO455Xxa2XBDEy3BMEs=,tag:eLtZxR152tIhoz67Nmf0kg==,type:str]
        device: ENC[AES256_GCM,data:LRwV,iv:c/F6USOJ2FVjlJCe+p0cnd3uvNofjmXRsFDK4WyK5XQ=,tag:SIOz446NHEvCGBT2R7dAiQ==,type:str]
model:
    width: ENC[AES256_GCM,data:otkj,iv:N+S/zBHOAP7azPeofjNaFjJgz3rLpGXI90ehtYWEMZY=,tag:rJepbS1QJWWfLR0N28vs9w==,type:int]
    height: ENC[AES256_GCM,data:Prqn,iv:xHk44mP3HpyDeeFwOsqzBG55aau+c9fInRckMec+tes=,tag:9ubVAgT5lVEHt/L16iDnkw==,type:int]
    input_tensor: ENC[AES256_GCM,data:aZyQWg==,iv:OM8HHArjrBR2c97o5ZqDtDJURI9hRrfB7tfN3Lq1Nsc=,tag:UgFQizrjveIZFyT0EATD+w==,type:str]
    input_pixel_format: ENC[AES256_GCM,data:KKSU,iv:GFW0lVqBzFbH9B8QLnq3gSnAKPbCBHSx2iblKUdpetA=,tag:CaCZlelv58UfqUq2/TpUMQ==,type:str]
    path: ENC[AES256_GCM,data:7s97hD8V2+5dyaxj9W48CbQY3d0IIjOMwHW/50ihS/fjv1YohxGzqg==,iv:a3IwGgDlHARdsE4bVl1GAI8Tnp7Nk0f3h5ZXMWfuxSo=,tag:iqNjSnhlN0fgvAi8/SiUAw==,type:str]
    labelmap_path: ENC[AES256_GCM,data:VwB1/PeL5DOFVraVnbdSQGd+ltFG8FOLdVA336MUzLuZVw==,iv:Qt2h5NloTny4+0FhyQsqP6Bu7pKo/ZorT4A86KAHGcs=,tag:ZJg/iW8uZhhTPpVAmM6ziQ==,type:str]
go2rtc:
    streams:
        garage:
            - ENC[AES256_GCM,data:BVvqog0omKDc0OYF21x3qKFn5fNJmHlMZxN2P09QmiR+VW9GHhMHDhsc/Qe9xbg6tSkD,iv:EwqoLQctwBmD3KsBQdN9UCsBfy+b9xZE1rTWhb0deTQ=,tag:yr8K54LDgUAc7vL1yOR+qg==,type:str]
        doorbell:
            - ENC[AES256_GCM,data:NUW8DkSPepg6ARZp6YdePcFUxT6+mjRJR5i3vifxa3OqglruZJZxUjg=,iv:1j0iVKOOSl8fNBmRqyD/bY1K4DBBDszk/AJjo3FFc+0=,tag:aC92ZT/uEuJP4QVXYjd/3g==,type:str]
        packages:
            - ENC[AES256_GCM,data:y1ehQq0RmUFK0cBqR/BOlOYkQRUgxbMutdy3pc4SZAKHAK67+N7Fy+E=,iv:jyBbbUMI89U5Q2ex7o3mVwQUM8LRXOhO6Gz3Ig+7vJc=,tag:Bau3s2SJqLdAtrQzQUoedQ==,type:str]
        street:
            - ENC[AES256_GCM,data:JunYX8LMnM5XT/gp8YLo3CyclKfusIZe79QvqxP1K7PidqvBITuUyZU=,iv:JBW0OC62s6nCGtE9uozigkfXzOxwTu36Xt1so459lN0=,tag:a0DIkbBHQKbxdudMx8Y63w==,type:str]
ffmpeg:
    hwaccel_args: ENC[AES256_GCM,data:s1+KKVtwF/xkCWJfDv+EqpLG8SKG,iv:0IE3hxx931HUuEcUabi+bDVqGl5153vqFVbvc9uVw7s=,tag:P2tAR2DU+QIiB0B+9OT1iw==,type:str]
    input_args: ENC[AES256_GCM,data:6ASHRW2aH/fq18P8ykTKg1Z4pOw=,iv:RsZHJLv7U/zc/fH5xz1CmnKv3pZlgioUreHEr/QR5Yw=,tag:ikMoelC4l4WpcjWt7bwflw==,type:str]
cameras:
    garage:
        ffmpeg:
            inputs:
                - path: ENC[AES256_GCM,data:jP0qtCviupIjSZzYUngoUoCk+Ebo2chR7lXajQ==,iv:onl4DynAcBAJdmnUvncoVyuxXdRrr/pYHnSIjtMPSY4=,tag:nXNyVZFMHt/+RuEKKSOF0Q==,type:str]
                  roles:
                    - ENC[AES256_GCM,data:vM8Qe0QT,iv:FqCfFTyDwdCs6kTrTJwsOPwTkxbWljyqa1YnnXX9RBY=,tag:W8pLNTSC7w0pXXsFMGEv8A==,type:str]
                    - ENC[AES256_GCM,data:mvpnaCpV,iv:TVrMwDJbg+2Ji47UHGi/APThBevxpOW62D3otXLnyhY=,tag:uT1PqHH72DVkxfU8UNGPNA==,type:str]
            input_args:
                - ENC[AES256_GCM,data:niPKoI8w76ui5j4OheKw,iv:Rj8h+g/2zw5hvVENYrEstasJibVcbUhSxrk3WiYyx2k=,tag:r5CUoOaOQtxvF3KDBTo+DA==,type:str]
                - ENC[AES256_GCM,data:XKnW,iv:yvk53TKIgOlkvHVNJV8EJTgh1hbEhkNvXxFo+kFzaaA=,tag:LEUUDxpFevOFb6sM3NT2OA==,type:str]
                - ENC[AES256_GCM,data:pSffiZZ/GYUSgfI=,iv:VGKay4Nj6mlLWonMSlCn7o3fxq/fGRR9dVu/CXZ5j+U=,tag:pkSuMudwMM9PzOXhpD/rdg==,type:str]
                - ENC[AES256_GCM,data:rwJ8zxtYvJNyWA==,iv:q1MT3G1hJERYyWUsU/o+l80RVCvZa6rJ5nzbWWdFyBQ=,tag:e287zhXsxf7asCHEsc6A1Q==,type:str]
                - ENC[AES256_GCM,data:UJRe/Zrri60wlWT1a5/TJdEgnhH2bWMrPRWUTg==,iv:yeD3QlE3eF3r9qFmRwGiR6X2fUY8LNUWE3O3G8ofh3g=,tag:/z7s66Sqgqvi9fWc2v43uw==,type:str]
                - ENC[AES256_GCM,data:wg==,iv:/TIP956+kYd21OG9dmaVkR/mzBYvtHTJ477+dHOhI+g=,tag:D2DqXTLs3NjQ4rxtKOGgWg==,type:str]
    doorbell:
        audio:
            enabled: ENC[AES256_GCM,data:Jf54/w==,iv:/4qfeUDqw/VIZjyCtvd+W4DGODPBaWR8HD9bsw265uE=,tag:QMvj+wUFUMyvbQbQz5qhAw==,type:bool]
        ffmpeg:
            output_args:
                record: ENC[AES256_GCM,data:3+u/uzU0uSny31xC+JPLtl9WiaTzOw==,iv:KEZmJFq09lvXIUBFL4j+xYRp92eGdAkZ/G1TTe3muJA=,tag:IL/kppl0nd/+/H8SHELXkQ==,type:str]
            inputs:
                - path: ENC[AES256_GCM,data:9z8bj2RI4KsMydv0a4tdXOfZqHAHVL9G6Dkmfgw7,iv:WV3bternw6Ug/xWe9qalk/D2zTvxSAJJmbQwUJnj++A=,tag:uyakW3iVi6wMa0utPU15Cg==,type:str]
                  roles:
                    - ENC[AES256_GCM,data:0GAARqY=,iv:VDc4PyAAn+G5M/eaLW9qPFDPbxzMMRuYWmSiNNNoGvM=,tag:AqWc70vtxSnhPupkoPBneQ==,type:str]
                    - ENC[AES256_GCM,data:VtwWBi5h,iv:2Kk1inCErmfSeFp5ErWnnAZ+PpyLgMDa22EAT/+4InI=,tag:NqNc6FRfkjlfQK+vjZ5/+g==,type:str]
                    - ENC[AES256_GCM,data:SR3ZouN0,iv:Ff979XX4MU6Lm8bcAbw0tzOBDK+0AuUl8APNKNIDwGE=,tag:RUtXoGe6QdpswP082Ukdsw==,type:str]
    packages:
        ffmpeg:
            output_args:
                record: ENC[AES256_GCM,data:38zPZS9oGVWLAK572bf9R/6SLBFUKQ==,iv:zfZXThJ9b/H2izQwed0s9sr9YFfeYPLFSmUlCZAbMf4=,tag:/n0Sn7wmk0bsQsFm8DHlaQ==,type:str]
            inputs:
                - path: ENC[AES256_GCM,data:cas4ORIooUBEMTuyfR4BXkeLkA+YoelnMRTPX0Bf,iv:VEEZ+eJBgDkuRBooljLrV2dRRagtvgDT0mcxtEYYPH8=,tag:DEQztVBFhhbsdcZbGUQBcA==,type:str]
                  roles:
                    - ENC[AES256_GCM,data:BE34MktD,iv:HaFAM+pL9h1iA3a2D3hQ+d1dicN+o33flmp+uB47VEs=,tag:X4q7j+EbrzmooUSGaUUcbQ==,type:str]
                    - ENC[AES256_GCM,data:lIUp8Qk6,iv:IwZx3jZqRwqkx/Gcp6Yf7xR902JrBIGu/l5WEVvI1bk=,tag:6HvzAZL07gLFSuEE7QTV3w==,type:str]
    street:
        ffmpeg:
            output_args:
                record: ENC[AES256_GCM,data:8H+1hdFC4+pdmp/PdU+9Q6rD16OjQQ==,iv:DDZrhzFekGNyo02wZeyFdUyn63JrHn0aM6ys/BYInxo=,tag:+1H/HFd1UyeJtJLPbD+cqQ==,type:str]
            inputs:
                - path: ENC[AES256_GCM,data:btBk3KN+rnXRyZ6QeSNadi4eYgHr4ghpPfBHOw==,iv:PkRmPG3o940TcBU53N4Jk90/1TbDvvU0ErhCzl9vVCc=,tag:A9Fq5frYbSR7Uh4Rqk/wOQ==,type:str]
                  roles:
                    - ENC[AES256_GCM,data:MkVeV4ID,iv:g0Sbwr6wFo+coy56svPRxkiMVX/decjUup5uHb8Uai8=,tag:abZ+B//yxXQbf7F6/7hnoA==,type:str]
                    - ENC[AES256_GCM,data:73e4udBl,iv:1e+VQ9cXgEodcqrfZ1bSDrRAhUA8iqlI5qz0mawCgT0=,tag:J7msHSowo7Oeb7MII0CsBA==,type:str]
        objects:
            filters:
                person:
                    mask: ENC[AES256_GCM,data:GorQ2PPIJUE/K3Zqzj51aYjd3uD/qdqsTcrS9AqtRHTRhKx/gHp++VYMjb/s,iv:aJX4qbQVnotz/eAdkbz0TRmcUhYNu9YVhrQnjtQicnc=,tag:gZWW6JahjrKVMcuw8SVqbQ==,type:str]
sops:
    age:
        - recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNm5qTUJkazVuSlRwRWFL
            Tm5DS2sxOExiYlUvY2FiZzJuNS9nT2ZzNGhvClJPVjZsYjB2bE54cDhacm16ZjNT
            bTEybmk2cTJ2VllnZEtCRGZNbkdnUU0KLS0tIEtidXgvdFhNT3J0UnFKT0FzUkU2
            M21wUlk0YjkyY0RlWDhQeE1jemtib1EKCKDkOv0PlcA3hAqukiY0F+wjNUrIhzMJ
            VEWm2coDvWXapQ48AghT+5uxcyUtmX0x8voVcQLY3XZ6UylBOFyffg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T18:13:35Z"
    mac: ENC[AES256_GCM,data:f5eZ1HZ8wXmOIwX5aWe3FmoCyVe6EGt20Vz4D8kvecJAOJulcvxWiYh2JpBosytnuAlx2D+WA0/1MLQ97itRrLps2c+j1JhuHvIpIO3RE4v+P3v+Dvf+9CufqUqQp94hVyfVtIAZbWFykIZxrCv+gGJFYXzDNjLFGjF3Ll7eBX8=,iv:MbKR76hsr+S9njSIvt/oXUfrFxS7KCEe3YFEmY9G6g0=,tag:uyD+JUAzOC2pDi4wsf4WkA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
