#ENC[AES256_GCM,data:uNGOjdA=,iv:29YUC5oolEMKibY2ImtUN1uUR1NyQ+cX2HbjZon/eWA=,tag:vYN6/xHvR0r14SQ5aWsr+A==,type:comment]
#ENC[AES256_GCM,data:nmIuj15AxOTDulkyfaXkTtU/gVrcgDpo3lK4BabevIH6n5Nr/nZX7ug+3aLXMwcBVblDf6QJsb8i91sY7o0r24DXHcq3Zu9riA0PT9OcI9HfN0KlTMTgpodEAiLvrgwY,iv:tN5NhsInxIy6wB/un6rDk3ap6ajlh4hDoWNt0Gr3goo=,tag:nwokdD8cA8tR2dZ7s+4QfQ==,type:comment]
ingress:
    hosts:
        - host: ENC[AES256_GCM,data:ygYb4Cohzxqr2sMcxgdsyZz+xApxk50=,iv:EBN8a8qGREvvXlxOBisbF8gNXRATC/h/fInEGTQyZqY=,tag:n2mapQIgMThJUhjh8AOl1g==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:+A==,iv:zjxz9Pk1H6NFBjkXljzQDhbKoKSjfehpMSoPiRV4AkM=,tag:4Y787gbbKIt4tOJd5Rv08g==,type:str]
              portName: ENC[AES256_GCM,data:NLC1ug==,iv:8KDP+1/fPH2aUWGGZFxe6zLVvxykOm44raRFdH/x9/0=,tag:Xa1ritug7F39m7DyhYPdiA==,type:str]
    annotations:
        external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:4smjrMdS2C2fUdVIQ/htj7arCMijOx7h,iv:J/hbTpBkB4PavNlUr2gaWkzH8E/YCxPS8Is9mzd+ALg=,tag:0ydQb+47LUHCBSiAxxEPaQ==,type:str]
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:siOeZN7XGXhiYezY7xfB78tJYZf85Q==,iv:E8hUuxWqTkqpyti/LLdHDCVFyQMV8JHWVKH0YnQpQFo=,tag:MpTUyzWKyF2pIBrCYYaiDQ==,type:str]
    tls:
        - secretName: ENC[AES256_GCM,data:3SfivD4cDHKkA6s=,iv:O2A3K3b8UbxUN1Xtl9Iio2iUO7oYipQW5bYBo8PqWjo=,tag:1E63FpuUUjSp5bqPnKzrCQ==,type:str]
          hosts:
            - ENC[AES256_GCM,data:sOkvjqO1rQRearAig1NmXJieoe7UU5k=,iv:El5tzBjkUnDPr+50l0d2PUiJ9fKrsAO6G/HPWqaaUPk=,tag:zZvkcZGN08i7BivPPbYGjA==,type:str]
sops:
    age:
        - recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSTVjRXMybTlpK1g4cnhV
            RitjajBUeDE0VitjM3ZTVU5CZjNIQjJKK1c4CnZlQkNSaHNSbHFGMGthVGh6UUxl
            NWJWeXhxL0N1RlA3dFlZYVZIcFA0M2MKLS0tIEZCL245SzJoQ0pYb0I1YWJQZ1Na
            QjI3VHNoRFlIanhlMFZHVFcvYWhkUjQKMestrDb9KhNR6Ef51nHWrmgtI4tqqRuH
            4QbhI7ApKj13arQ3zQJnaHbLJPbqWqSSjqYlMbGGreek7fPlR5cGww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-03T19:14:05Z"
    mac: ENC[AES256_GCM,data:mbGsIGudTlmBBWTm14ritW1pH68KMP5K2uBV401dGhzHpMntoQQvmcdJngfeyUZPJvoFzCQ0FsRXAKnQtTxdlH1/N67zsTGVDmESkmiOgL6zQSQ3X5gQ5BOvOa7xDhaU3v51TpoH3wnkA8uzFzFooWw/2zOGRDVmZySngHZAeFc=,iv:VrT8vGA7pwER7uF4O7beEQ5tYuTh3Mjo6M90sJpQdOs=,tag:3oNWQrd5P/tDslKIr6w97w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
