image:
  tag: 0.17.1
# strategyType: RollingUpdate
securityContext:
  capabilities:
    add:
    - PERFMON
persistence:
  config:
    enabled: true
    ephemeralWritableConfigYaml: true
    size: "10Gi"
  media:
    enabled: true
resources:
  limits:
    deviceclass.resource.kubernetes.io/gpu.intel.com: 1
ingress:
  enabled: true
