commonLabels:
  sync-stage: apps

repositories:
  - name: authentik
    url: https://charts.goauthentik.io

releases:
  - name: authentik
    namespace: authentik
    chart: authentik/authentik
    version: 2026.8.0
    values:
      - values.yaml
    secrets:
      - secrets.yaml
      - ../../secrets/authentik-postgres.yaml
