authentik:
    #ENC[AES256_GCM,data:M3FMu9DgIMkUhqP6nEytQSwrNQO6IWg4/jAcfrjJwapVqjmfLohG6iOL0xwjMztuQLxaOu8H264SPHuetNaeDBUX2P4XQXJO6ejoaQBanksYK6c=,iv:IjGLKyazEnA471f5c/e7tLikKj46t2e37yrEt+7ZqXA=,tag:EXbOY3CbbAoOIymzG67+Yw==,type:comment]
    secret_key: ENC[AES256_GCM,data:TUtcYiBtLs37eUDlrMOneX/7waVhc0I3qtzpp7cxO5bIxdODW9uLE24uMqLu5U5KtAFHf5xUl+81qMRAsQmkwFLtFxQ2bE9u0k4Jd80VMRIdW8xMw3A=,iv:rIIulpL5AuczrCw5SF2rFTvDIuqD5BrQ2EMRzo9pqXA=,tag:osqV1g19TnCdGZplwOFCyA==,type:str]
    email:
        host: ENC[AES256_GCM,data:X9w2dRc0J8H+L4xk0y69Szw=,iv:SVmLZ4L61+hp25rrqsIMclELLPN53ozMre46VcLymzE=,tag:zH5Lx+BmEpZBaLmJiJh+zw==,type:str]
        #ENC[AES256_GCM,data:rmYffeV0tETMWi+m3UZ8OhS42cQ78TJIXX2FQ5AsRSMKxhNEnx/x7D/oVW+u6zuVQ5Hn0PakoroNUA==,iv:DFuJzTFuMWnC4+HAubNy5ojn+D+FTe+cuaSt1bhCo3s=,tag:GHzrfc0nCbD/sFKfGadplw==,type:comment]
        port: ENC[AES256_GCM,data:pcIR,iv:UiZ5p0CLqyQXGaFH6V286rXaelEJKCokawRA8mb3dYw=,tag:Gv/VyRRYCrYBnf3JY8jBNg==,type:int]
        username: ENC[AES256_GCM,data:2yTyzxMLesgwYLMj/soJSTA=,iv:71WV1kpTeO2l/qd6gwONB4TY62f5NjiIb8tKbQ52nco=,tag:MFep1OQUWrCtotZkr82adw==,type:str]
        password: ENC[AES256_GCM,data:Vma9Yke7xMWviaxoxJatog==,iv:HMbK7iYWgi/g1MqIKaoZyQ/ELjBtf5TobvK5O8KAWgk=,tag:JG7I8cNyg5U3oIIB/moHKA==,type:str]
        use_tls: ENC[AES256_GCM,data:NPQX9WU=,iv:ueaTtlxeJ8hM3swN10iwowByhe0452pYnGVudkRlqrQ=,tag:GEJqJM3K4gx4a6pkD4ZpsA==,type:bool]
        use_ssl: ENC[AES256_GCM,data:0VIxDg==,iv:0Fk8TEAkcSipGTW2oKf3S9uff++JFOfcCgkPJFY0ce8=,tag:0hfTH3Ldylcd7CNyguVM2Q==,type:bool]
        timeout: ENC[AES256_GCM,data:sS4=,iv:esw1f+TlCy7aGw7Y39kq12msjwBVdVaR8HDyAFzP3QA=,tag:/wBR4qzdcBPJBksDgQFSGA==,type:int]
        from: ENC[AES256_GCM,data:zKahC5ZtTZ2aQIdPkJjDxwnA8g==,iv:lwIS905ny3TLZur/JtzrApAWfhAudiK+q2FHLvlvK8g=,tag:N70ZgZvj3dHE1OXdq1PV4w==,type:str]
server:
    ingress:
        enabled: ENC[AES256_GCM,data:Dmim1Q==,iv:qJBJGeUk9aaJhuCaGS9IzwfWG2xrRoQovykbmB2kg7g=,tag:dagDKQ54dwaRVjAD9Vwv7Q==,type:bool]
        hosts:
            - ENC[AES256_GCM,data:EwUrsjvw+fws6vnWucuwyfyaLos=,iv:3web6ZMCQYbsMAkMz5wtUlfJ+5nHTu/Y7Li2HGH0Npw=,tag:GRq0Vd6vd4SzUhSP6gdgbQ==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:l2g2/HVo9KXuVY9UrizTAwXWaahehg==,iv:eceytRiWixZJschhIpff01jKujf9rU3HayqJJXC/OO4=,tag:anAMq+P2Qc6bLuY0Indcxw==,type:str]
            external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:/XlxLW8OUcFH2FGrkfiOurYbMLCs,iv:FSHASZuaZzIuG4RI3qcSdb7DGESeBdM1drGUDbwp+ok=,tag:hf05hYars8D/cef6xjF0xw==,type:str]
            external-dns-cloudflare.alpha.kubernetes.io/enabled: ENC[AES256_GCM,data:U7tB/g==,iv:ZwWYNscw9S165h2AYfeLC46bLOuMZZnzbILm2Dx2f80=,tag:OuPLwAVM2rwKgTv1+UuPhQ==,type:str]
            external-dns-cloudflare.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:0hjEJV5ccpLaOiS6AsUlTz/oWNs=,iv:9PCj70qdYg/cm8ugaZip9x6g+b+OcbtFnOTbESatds0=,tag:D3oFXXYK8BlhMAlX/2b3zw==,type:str]
            external-dns-cloudflare.alpha.kubernetes.io/cloudflare-proxied: ENC[AES256_GCM,data:45sDbg==,iv:MAjioh63zIcwhCayY08pi8RZgzWLoKVZV6JgyHRWQRw=,tag:lB/Uaxy+4XbKUCbsBeKK4Q==,type:str]
            external-dns-cloudflare.alpha.kubernetes.io/target: ENC[AES256_GCM,data:ZaJPj/wfV3hKtmfmvhys4Ozz4HnyLraqK7+9pwj2pf440ZNh7Oq7K43pXLFh4o63mFAVQ5c=,iv:hNNtpXJz1N6f9dYq2kQW0kG6mtvY6qV1oblq91MNRKU=,tag:AiCohmLHi4EdidhTENJQhQ==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:bBx43ekRc8lfo6vzLQ==,iv:RX5W7aLcSVI5ceGEidxuMWN7LtOed26WgmkP3s9MWdw=,tag:4O0AF+3pLweCUt4cEPYGoQ==,type:str]
              hosts:
                - ENC[AES256_GCM,data:rUN+e0Kt1GD5DuVbcVluatv+zK0=,iv:4q9+dYzIfqTFpOUnucHiflYnDgYM0tyeVXB0nBZKr3k=,tag:ifa3K5CWI2QeiE8mKuq5cA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK0VFSm1jYkc1U2tXTnpm
            T29VL1pFYytIUmVlZ0VONk8xb2lZb1pKUGxNCkpZZnNwaDR5VGpoSWRGZE1OVER2
            R1FlVkhHWFBUaFJXb1pOWkdPT0o1MjAKLS0tIC9xa3pzVUEyck9HendVN21BSlU4
            Z2dMeERpY2xtbkxzalcvbERNbEZydmsKkrmk70FrSt5ig5Ad8LEMYOLHIkkFY+nT
            +AubFzB1ni/O90KbiIo8vQ4EeoHRdxA0H5Q+6FGg3OrlFsAGJeOKgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-07-05T02:47:52Z"
    mac: ENC[AES256_GCM,data:HVGKhJ2QkyoY1hFo1nZ3N8x850tu3B4vumquVjFLm+BzssYyI+iuiJOuEFf8RC/QvjJjUBOeOKlIDLFx4eokcuPs1aHVUEr5dZoawvmS/UMX+kQJHzfegU4IRBmJYEkEZrkjRfOd9plbPR5PXM4YylPgVr1iyx2d0AHMVPOR9Cw=,iv:GadOn7ETG+WzS7jzHBj5vNnWziPtxq8YGHQZUCqaobM=,tag:E9Vs8zS9FKKk2SYZ6guEBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
