authentik:
    #ENC[AES256_GCM,data:M3FMu9DgIMkUhqP6nEytQSwrNQO6IWg4/jAcfrjJwapVqjmfLohG6iOL0xwjMztuQLxaOu8H264SPHuetNaeDBUX2P4XQXJO6ejoaQBanksYK6c=,iv:IjGLKyazEnA471f5c/e7tLikKj46t2e37yrEt+7ZqXA=,tag:EXbOY3CbbAoOIymzG67+Yw==,type:comment]
    secret_key: ENC[AES256_GCM,data:TUtcYiBtLs37eUDlrMOneX/7waVhc0I3qtzpp7cxO5bIxdODW9uLE24uMqLu5U5KtAFHf5xUl+81qMRAsQmkwFLtFxQ2bE9u0k4Jd80VMRIdW8xMw3A=,iv:rIIulpL5AuczrCw5SF2rFTvDIuqD5BrQ2EMRzo9pqXA=,tag:osqV1g19TnCdGZplwOFCyA==,type:str]
    email:
        host: ENC[AES256_GCM,data:X9w2dRc0J8H+L4xk0y69Szw=,iv:SVmLZ4L61+hp25rrqsIMclELLPN53ozMre46VcLymzE=,tag:zH5Lx+BmEpZBaLmJiJh+zw==,type:str]
        #ENC[AES256_GCM,data:rmYffeV0tETMWi+m3UZ8OhS42cQ78TJIXX2FQ5AsRSMKxhNEnx/x7D/oVW+u6zuVQ5Hn0PakoroNUA==,iv:DFuJzTFuMWnC4+HAubNy5ojn+D+FTe+cuaSt1bhCo3s=,tag:GHzrfc0nCbD/sFKfGadplw==,type:comment]
        port: ENC[AES256_GCM,data:pcIR,iv:UiZ5p0CLqyQXGaFH6V286rXaelEJKCokawRA8mb3dYw=,tag:Gv/VyRRYCrYBnf3JY8jBNg==,type:int]
        username: ENC[AES256_GCM,data:2yTyzxMLesgwYLMj/soJSTA=,iv:71WV1kpTeO2l/qd6gwONB4TY62f5NjiIb8tKbQ52nco=,tag:MFep1OQUWrCtotZkr82adw==,type:str]
        password: ENC[AES256_GCM,data:Vma9Yke7xMWviaxoxJatog==,iv:HMbK7iYWgi/g1MqIKaoZyQ/ELjBtf5TobvK5O8KAWgk=,tag:JG7I8cNyg5U3oIIB/moHKA==,type:str]
        use_tls: ENC[AES256_GCM,data:NPQX9WU=,iv:ueaTtlxeJ8hM3swN10iwowByhe0452pYnGVudkRlqrQ=,tag:GEJqJM3K4gx4a6pkD4ZpsA==,type:bool]
        use_ssl: ENC[AES256_GCM,data:0VIxDg==,iv:0Fk8TEAkcSipGTW2oKf3S9uff++JFOfcCgkPJFY0ce8=,tag:0hfTH3Ldylcd7CNyguVM2Q==,type:bool]
        timeout: ENC[AES256_GCM,data:sS4=,iv:esw1f+TlCy7aGw7Y39kq12msjwBVdVaR8HDyAFzP3QA=,tag:/wBR4qzdcBPJBksDgQFSGA==,type:int]
        from: ENC[AES256_GCM,data:zKahC5ZtTZ2aQIdPkJjDxwnA8g==,iv:lwIS905ny3TLZur/JtzrApAWfhAudiK+q2FHLvlvK8g=,tag:N70ZgZvj3dHE1OXdq1PV4w==,type:str]
server:
    ingress:
        enabled: ENC[AES256_GCM,data:Dmim1Q==,iv:qJBJGeUk9aaJhuCaGS9IzwfWG2xrRoQovykbmB2kg7g=,tag:dagDKQ54dwaRVjAD9Vwv7Q==,type:bool]
        hosts:
            - ENC[AES256_GCM,data:EwUrsjvw+fws6vnWucuwyfyaLos=,iv:3web6ZMCQYbsMAkMz5wtUlfJ+5nHTu/Y7Li2HGH0Npw=,tag:GRq0Vd6vd4SzUhSP6gdgbQ==,type:str]
        annotations:
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:l2g2/HVo9KXuVY9UrizTAwXWaahehg==,iv:eceytRiWixZJschhIpff01jKujf9rU3HayqJJXC/OO4=,tag:anAMq+P2Qc6bLuY0Indcxw==,type:str]
            external-dns.kubernetes.io/hostname: ENC[AES256_GCM,data:cvf1KViVSLv41OQSCM4+zFDUVjyu,iv:NDm4XnuwrqMH8ql1EXZrHvzLYn+CSWfFA3XddrSBeLI=,tag:Ni0RwzKuwlzCMXwsPechPg==,type:str]
            external-dns-cloudflare.kubernetes.io/enabled: ENC[AES256_GCM,data:kqBbLQ==,iv:pYoARAbb2xTxs1Rw8ECp5q4p0PXHk4VfC/TFRwFsOEQ=,tag:rXUQJ9KK3ftNrsXAdimRaQ==,type:str]
            external-dns-cloudflare.kubernetes.io/hostname: ENC[AES256_GCM,data:qsGoZQ0+2ppAuxGYaZkWY205f/c=,iv:EWIK33yJQ/U7cA1mnxtbPPShGY19BLllAe+EHfkbohw=,tag:mnRvsg4FAi7X4/S9V8vQlg==,type:str]
            external-dns-cloudflare.kubernetes.io/cloudflare-proxied: ENC[AES256_GCM,data:zgr6JA==,iv:tzJxLw1jQrWjjN3UHMQKuvoCt6UyUg0x9lviWPr3pGI=,tag:dWjGVqWnRKh/MX8ezBMJpA==,type:str]
            external-dns-cloudflare.kubernetes.io/target: ENC[AES256_GCM,data:YjEFFEF+B2jqaWppM2lJUcQj/oFkJYF0yBueDrQMNPqKaYSNtreUgEdoC1STod7QvxlMjPU=,iv:b10s3N/4VQOoS9m4Hjmj2yp+OtBRBrHHyIlpCfAQDxc=,tag:JWvxDbugeBdSWXqS6M/QQw==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:bBx43ekRc8lfo6vzLQ==,iv:RX5W7aLcSVI5ceGEidxuMWN7LtOed26WgmkP3s9MWdw=,tag:4O0AF+3pLweCUt4cEPYGoQ==,type:str]
              hosts:
                - ENC[AES256_GCM,data:rUN+e0Kt1GD5DuVbcVluatv+zK0=,iv:4q9+dYzIfqTFpOUnucHiflYnDgYM0tyeVXB0nBZKr3k=,tag:ifa3K5CWI2QeiE8mKuq5cA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyK0VFSm1jYkc1U2tXTnpm
            T29VL1pFYytIUmVlZ0VONk8xb2lZb1pKUGxNCkpZZnNwaDR5VGpoSWRGZE1OVER2
            R1FlVkhHWFBUaFJXb1pOWkdPT0o1MjAKLS0tIC9xa3pzVUEyck9HendVN21BSlU4
            Z2dMeERpY2xtbkxzalcvbERNbEZydmsKkrmk70FrSt5ig5Ad8LEMYOLHIkkFY+nT
            +AubFzB1ni/O90KbiIo8vQ4EeoHRdxA0H5Q+6FGg3OrlFsAGJeOKgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-09-12T18:32:37Z"
    mac: ENC[AES256_GCM,data:GsLTQpHCWf6oAH2toSra8YILlKE0nVZUXB9PG32mDwdClFllPqmfS2/F0Ze1B0Wjq6r7UZRuEvpdLbzx9qnOnyU7IQtUFYj6VCt0BZJ7VsMyaC6vDu1t4vqMUhFHZKVNy34vpOug3RhaMTaNOmZcs3ZmP/CadzRE5vr1G+YiKSI=,iv:IVqyoWmmAUb279bgqcdAt/FapfgeWDup71As94WgmtA=,tag:9kzqqrkHK5ltYKAi3zU/BA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
