commonLabels:
  sync-stage: observability

repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: tempo
    namespace: tempo
    chart: grafana/tempo
    version: 1.23.2
