repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: tempo
    namespace: tempo
    chart: grafana/tempo
    version: 1.12.0
    values:
      - values.yaml
    secrets:
      - secrets.yaml
