adminUser: ENC[AES256_GCM,data:j7Co81Q=,iv:yZXxzEghancnf3WukgjITsyqUIXqe5luBnznlmVu+CU=,tag:g4G0UbJvKFeozsNGX8eiCg==,type:str]
adminPassword: ENC[AES256_GCM,data:bXtm0d8h3w==,iv:SwQrDlgBksDWiqGyGuORBXuqgCnbS4wNwBVJv3/Tp+k=,tag:MzyrStvHR2Z4lQbFAj3v2A==,type:str]
ingress:
    annotations:
        external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:1U3XXQEMcZbIuQdBNMGIFQlQeEHP1aQU,iv:oVyqzMAr8YzZSI7tUqz0Y7lsI293LoiilPxTCm6BFys=,tag:FaYMDJNFWcOGYBTqbZD2tA==,type:str]
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:wzJrm6ReJ7JEt5xL4lZbfkqD2vOlYQ==,iv:69uE5doZPWf3ETNPTyklkaOekuEPTd1iluNTbWnhQvI=,tag:g+HOtcOa2vAbdW8LMC1Dhw==,type:str]
    hosts:
        - ENC[AES256_GCM,data:O3KN0UOAovHexGcjFhmWaSAvMOjxxS4=,iv:1sNp72T6cgnLMu3fZ4SCpnr7YuJC28NgHaOEhSeMja4=,tag:g7exWiIZm9cam6Ke5qzX1g==,type:str]
    tls:
        - secretName: ENC[AES256_GCM,data:md+9sdn9rgftvFo=,iv:dcphP5c2RYd+eKNRTtUWclzO+BfX7P5gDdX/yxxTfIU=,tag:HiyfV5womnDQvnP7+noNPg==,type:str]
          hosts:
            - ENC[AES256_GCM,data:dqzhkwMLKGqDork+fbTay+UfBEFuSo4=,iv:t0VdVWbPGScWGLFCVF1VxKWcqHBD7ElqL3YM4XkOCDA=,tag:7zNm/Ibux3fhMSgLwfXLSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeEMvR25IeVUzY1FCRTl3
            dHVRb1BiaGttQjljRE1DaGNQMkJpUWNmMTFZCnEwaTVlbXJ6b0dTVzRJdkE3VmNu
            cHYvejJBV2lhZmw0TWFWb3YwWWpPU0EKLS0tIG9TaHZtUENYZ3dLTzBxMTBJamdw
            VlNQc0MvUFBQbld5dSs4Qk1wREhLQW8KQLZb5cXB498/H9LP6mZb3sP5trUVEWq3
            LfvTpauRzh2/75oFppoM3otiN6eyU47z1pf1oqEHxQakO6h9s7jMnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-11T02:46:42Z"
    mac: ENC[AES256_GCM,data:gPh3EklQSoEPoMM0wfwI2iFkyoZ1xRgXEHXKjsjwPyjik0yWvayIIkvWee83CUMNFkcVuceFF6cFCEPD9LM4qaS11vQSJxV3XXkQCMMKhFNkEMx0xyFggq7Hjj4aOlYCm8tVE7b3KyYwh2G/GOjDpaJXHd+d61eBOxg/eClRTHg=,iv:uXNTEgSxbxgPA+CSSw31nwIexG9QidOVlubnheKhu/c=,tag:P/5QGMkYRVyNGV7TUCjcQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
