{{- if .Values.role.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.role.secretName }}
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.authentik.postgresql.user | quote }}
  password: {{ .Values.authentik.postgresql.password | quote }}
{{- end }}
