commonLabels:
  sync-stage: system
releases:
- name: intel-gpu-resource-driver
  namespace: intel-gpu-resource-driver
  chart: oci://ghcr.io/intel/intel-resource-drivers-for-kubernetes/intel-gpu-resource-driver-chart
  version: 0.10.1
  set:
  - name: cdi.staticPath
    value: "/var/cdi/static"
  - name: cdi.dynamicPath
    value: "/var/cdi/dynamic"
  - name: enableDRAExtendedResources
    value: "true"
  - name: kubeletPlugin.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key
    value: "extensions.talos.dev/i915"
  - name: kubeletPlugin.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator
    value: "Exists"
