commonLabels:
  sync-stage: system

repositories:
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

releases:
  - name: external-dns
    namespace: external-dns
    chart: external-dns/external-dns
    version: 1.15.0
    secrets:
      - secrets/secrets-digitalocean.yaml
  - name: external-dns-cloudflare
    namespace: external-dns
    chart: external-dns/external-dns
    version: 1.15.0
    secrets:
      - secrets/secrets-cloudflare.yaml
