image:
  # repository: ghcr.io/linuxserver/calibre-web
  repository: lscr.io/linuxserver/calibre-web
  tag: 0.6.24@sha256:71cf33758891aa4fcd9dace41bbbc1aaf8faeedf78fff9f1a12f46cfc9156b97
env:
  TZ: UTC
  PUID: "1000"
  PGID: "1000"
  DOCKER_MODS: linuxserver/mods:universal-calibre
ingress:
  main:
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
