image:
  # repository: ghcr.io/linuxserver/calibre-web
  repository: lscr.io/linuxserver/calibre-web
  tag: 0.6.24@sha256:fee2cd6fc8264a514255bfa6ffa6ec31dcc6de64b89b037924b1ee76eb81f532
env:
  TZ: UTC
  PUID: "1000"
  PGID: "1000"
  DOCKER_MODS: linuxserver/mods:universal-calibre
ingress:
  main:
    annotations:
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
