commonLabels:
  sync-stage: apps

repositories:
  - name: k8s-home-lab
    url: https://k8s-home-lab.github.io/helm-charts/

releases:
  - name: calibre-web
    namespace: calibre-web
    chart: k8s-home-lab/calibre-web
    version: 9.1.0
    values:
      - values.yaml
    secrets:
      - secrets.yaml
