repositories:
  - name: tailscale
    url: https://pkgs.tailscale.com/helmcharts

releases:
  - name: tailscale-operator
    namespace: tailscale
    createNamespace: true
    chart: tailscale/tailscale-operator
    version: 1.76.1
    secrets:
      - secrets.yaml
