oauth:
    clientId: ENC[AES256_GCM,data:nWjRy2IGbr7pTZSeidUpiQU=,iv:A4xLJt1bl9xiIxoXP9iF4MzGxkzlNbMWfZoA1ytmcIQ=,tag:la3+/RCr4M/id04P1jRQEw==,type:str]
    clientSecret: ENC[AES256_GCM,data:R+bl7eqboNUjf3G9wT4ayhv1W9TZrNeluUOX/ha3vlUXrqnRMiK1sL9xlGwTvoToKvggWrG1PyolprWpJeRVIg==,iv:JlwoHbfgBoMcQJEXD28Z3jAWKEuaugKth00+iPE+YV8=,tag:HM+y7jl4T7/pJMj9vVgADg==,type:str]
apiServerProxyConfig:
    mode: ENC[AES256_GCM,data:rBKlXQ==,iv:pZ+zqtuhh3ayBJmyeneB7PBlHjfE8cPU3DxTTrZyFdk=,tag:wzYOZH/tLJapcy3z0ZvAjg==,type:bool]
sops:
    age:
        - recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWDVoMW9yUjd5TnpGYkRX
            NGNyWUt6bzVMMTZYVG5Dc0E2K2lDWUk1QkZVCk5JM2syZUtGdzJySURJbDQyMFFI
            Z2YyaXAyNGcvYTYweXpIQVhNSHBTRjgKLS0tIEVydTJRYWlQeGo1eW1aM2lRVHI1
            bHBPOUd1a29remtEWm5NREI1eFZRbnMK6ocri3f4l7czhO07Zm5mZ1MkTrLLxPFw
            o3hlvRYDO97XprQ08zjHimvXg/i4/ndHZSRWP/oME46xz3O4i+7/mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T19:46:38Z"
    mac: ENC[AES256_GCM,data:g4+R6A4DOw7+m+umf2JIBJFJqVXzYfPtEMujF9UgguBXzY+3ES+/0NGrwYQRTLtCkH7bSR/J0GQDdO540BezJCh0ZBpTuuP7qU73mTlQJpGT1sCtnjSBXh0fggS+SGzYRd2XLOtDDGv4+yBhV8Kp29/r68TlTaSXzkv1rE/Mic4=,iv:bWBil3ZwNtxtW3G+wVo+OsHR6K3p9EzcAkpWs2P6fU4=,tag:OUgugp38hEPhD1hn/sK0CA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
