txtOwnerId: ENC[AES256_GCM,data:doiyQgbpac0n++hN98fvvL0ZzmnKNP0=,iv:fH9RxihMO1GcmUqhUjZZcMVPFgUuJeBwWXdkU4+0iWU=,tag:QlCDGOyJwLRarfpnm+Esyg==,type:str]
annotationPrefix: ENC[AES256_GCM,data:lWpTfwphkLY9t4s56VSAVGYRsUFZJSzYW7yB+UM3DjwCdJrehj5SlRI4Xj8=,iv:SdQQxLnFBD+txu5juAUY+9oWpMb/7mazzEVEjFQa4CA=,tag:mjLEvG1mJvsYa0++k4B8Eg==,type:str]
annotationFilter: ENC[AES256_GCM,data:zVIPP2+u9Hu/TDZY4isg3aHWTQXINLbNcREzhogShYMtHU3JSD/k1YFLeFMi96LNHGQXfd2TNY18fgMKEg==,iv:lLKoAx4cVbnwrZeozQ/ZLjodnaHUPBrxEuoORuzFhw8=,tag:Vo7Vm/ai08BFPHg+hLz5WA==,type:str]
provider:
    name: ENC[AES256_GCM,data:GUNEeVkAXxWNcA==,iv:c2jxUEvhdkQ3wEyaimPqjIM5+Ye3iDomDIHaa55phS4=,tag:OMcbA3k+X6oY7hycN8Gt2Q==,type:str]
domainFilters:
    - ENC[AES256_GCM,data:sJjGpkGvI+T6eD0TrCPS,iv:NfQDioxN8XjaGBTR+78M35LzQaN0utVvnghlhOCTyqg=,tag:8EAvO/zjcqxuLkhs47QdYA==,type:str]
    - ENC[AES256_GCM,data:v3aTLQzSoBLM6G1QosTd,iv:7SBA2oociwnOoag5ymDZNh1jCa/zL2TQ/LgIWhOMkwI=,tag:Vgq4MsG77l3si/yoladURg==,type:str]
policy: ENC[AES256_GCM,data:3bvyig==,iv:WG4Lc6d/6Is6Ck7epdpQ0F3i7RXTp8GOtz0OlYYRX64=,tag:kOevwZo6Y5RjMhNmA3tJfg==,type:str]
sources:
    - ENC[AES256_GCM,data:yDe9K1LaMw==,iv:0au3BDVScGpPNpy2N7BbMfXWOuZYSxyOb0qllkcvZaY=,tag:ZDMmo4SegyYoeZoI2ZTXXw==,type:str]
env:
    - name: ENC[AES256_GCM,data:DrG7bMbnDGwYvQQI,iv:xMd9OB8lN7kJdmUk/eydZ361ryZoZhUPWgpXjCeOz+A=,tag:h+9Vu+8Kcm7SiUgTBNpeJw==,type:str]
      value: ENC[AES256_GCM,data:jYC8ijG8Ev2O9UtkBIJraYNXKSuAhbueWRLRTpRdKmFu00PLUQpzRg==,iv:O8i2wLJXoIjGFWwgy9a00YVC0OFzN25wPkvrPo9za74=,tag:Zi9vG0gdZ4r8O5zR1N1iVA==,type:str]
extraArgs:
    - ENC[AES256_GCM,data:1RD2+XoNobfeI+mK5/0SaWr0UFPzBUv4Adl9SFYeLmUI/E+MYwc=,iv:EwjAGXN/qScn8xMhH5s/34QbGCLfmmYfyKLTtF8ohrI=,tag:ZQ3MEt8wjwuaWQ9S+v/9Ww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd2E3N3ZVenBmYUE1aFdl
            emprOUtvQ3oveDNWTjlBUlZ6NWRFTnFrRlFFCks4bCt1S1p6aW84elVCTTJxQkJY
            YURnQ0kxc01ndmdLZm8yUDB0R1k1eHMKLS0tIGJzOElLVEM2QkN4S1pCUloyUUE2
            a3FtZWJWcks2TlFBRGszZjNQMlYybkEKr1gLtoYEVn7kqf9+OIbY/7M2ZeAsKJdK
            pXwu7SUvYZirDGJtS3211md17tsT7uyCo0h0LIkadhQEvPX4K1m+Qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-06-01T04:32:59Z"
    mac: ENC[AES256_GCM,data:8PmTvv/aHJwcegHxzSZzRICb+kjk+7zMTgHGAOC64ZLqEN9Xoty4+LoPnH8f8QPiRXwMd4QGr3Gy4Ag8h4+G6zzZkKtBl/QGSyQW8BIwiC3enxk0QyWZhEmJaGHu1enGy+Q1SyY6A7Y4ZtHfuE7rT5W4nBWRbZBqO4qzkaw/Eto=,iv:yGy6HP8qWC9yFDrsUZvecHkP0iFDPYDcyL6n17UDAt0=,tag:AcdxCO4/ZWRxbJktX6Urmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
