txtOwnerId: ENC[AES256_GCM,data:02rSSkdd2OS89501,iv:ySGCldg+IQTOM4s7T07gJPPL9uIHiI/zUEdep3NfG2o=,tag:/+Geh17FG98h3ue4EfKSmg==,type:str]
provider:
    name: ENC[AES256_GCM,data:IgojpF7o5UgZ5rG3,iv:Da5PPgmcZjL83fpWbZbMVq8bLquFffrU8H22jHnYVvg=,tag:+waIocaLmyWCcf/zDtIZeA==,type:str]
domainFilters:
    - ENC[AES256_GCM,data:d9skPuCE4FD86uM0lTLH,iv:7SKbJpjfSf0Ds6mThtkk567xW7ZDY7HTn6cyqGzE17I=,tag:OhSbFvxhsm1LSAOy5+mN3Q==,type:str]
policy: ENC[AES256_GCM,data:6Q4yWQ==,iv:TI/5o4Gm3eufJ2kuDLuE08RDwTRRO5gO4DuncEdWiWQ=,tag:J5FBXilaYR+uO2Th8HhSpQ==,type:str]
env:
    - name: ENC[AES256_GCM,data:3CxFwuoea5Q=,iv:v+/3Jq7OiilqNxCTykPsET2D57+VVzZzMD57wCXkWgA=,tag:F7heHFC+iOWouF8Th2ZbXw==,type:str]
      value: ENC[AES256_GCM,data:UfqBqZXhu0+LRdCgXGIkJiU6LXekPdEzgI4bbTnTOFUK4pbPGIDIs4TQoIeOACnJCCGktIqO4+FABxUTPtlUmsfvyL1qvLE=,iv:/ZcPSaKTQPcgLx8ctXOTZhAAjwqPaO/wZcBnlhrnKrk=,tag:brZJ/a6I3TuHVuZGZTZXoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva1A1ZEU2eGJESkNFR2Q2
            aW1pVU9YdHVPWkRGaDNRT0UxUWE2SjhxeG5BCnQ1aE5xSTJhSkhMZE1XTGZYWHpy
            SkJIbDBiNHE1SVdQeDhHWm5LRWUzUGsKLS0tIDVXeWlJRVNnTDdqREhVR0M3RXlG
            aXJDWW44YURXWno4QzV1MzJvczNjK2sKTEYUclTuWgCPc4c7cyzhzbbX/j2G8WfF
            /Wod7Y/7QzPF8qlPzzqYT/fxKb2QdboAf3qBc8AZsL19nxdyyKEsEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-31T00:59:04Z"
    mac: ENC[AES256_GCM,data:HNefDGGMYd7Rx00wqMZirBcWFwajdfUFW8zWN0NjZG5688D4JmC0UWp+2yj0tLKJwYh/ZC61xTA/rL869D6jgnX3HjgivJFhEmjRuCqebRbNFGGVK0+8OGfhtYZwTcZuXPMaMju8oqgNEzECNEEUtW2qwV41HDbagKIuC6FPkr4=,iv:Kc1cYNOznmLZD1a5TWlQPqeW/OzN5HUetD6dO9hcQYQ=,tag:6J3ZyNbiJSE4P9j3gatLGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
