provider:
    webhook:
        env:
            - name: ENC[AES256_GCM,data:s9CZXDLAsUMxFw==,iv:lU+XhCM6wQc8+ogYJijPtDo9qVi45CXP/GWi0udLyV4=,tag:gk0w8+PsGnT4EqwQnMlKGQ==,type:str]
              #ENC[AES256_GCM,data:PXO1XFGKOaFvm63Rr2sHlspXX0rRqVp7wc15qKlXQcpsuuU7CEs5jnPPOfX5ER148yGbccPWOmbCQeyhmPyFOV1Osdae,iv:r05SyozcfjvvlILTv8vW3QfS3oE0I/OdhBvIsvk2Nuk=,tag:Q3EuvfnLCJQ17geJMvjj5g==,type:comment]
              value: ENC[AES256_GCM,data:cKHDEJWJBD7Nf1aATrB1jJSopX56FYPkc2c3rl2DF1ma7+wHxLbX44c=,iv:ofva3FJ/mRaAW6892mWp6iNVTREyYqQeunEDpwBLLhc=,tag:E1VuDDWBv3XnuhR/v8T/zQ==,type:str]
            - name: ENC[AES256_GCM,data:llfX8zzWPUhPNv8hVA==,iv:6eCcZ5jQX1aqBkIs7C+o6XOMXwiAYXGk2AC0Cg37/IY=,tag:NKCR41lq8VoGATDzeII3ig==,type:str]
              valueFrom:
                secretKeyRef:
                    name: ENC[AES256_GCM,data:dclT0DGjfW41YV2VgzDrYQ==,iv:eYYkZcWmPRjHA2LFyue1ZJQ8M7C7MPJ6gtAp6qd+lWo=,tag:JPe215hOBePrQ2hrI7GtZw==,type:str]
                    key: ENC[AES256_GCM,data:WljpT1s0VCS6aFjMbA==,iv:BM4fLIxMlRKYxLhWz/vzVpMKzySnkRzUwTQiINFUaQg=,tag:vMDFdgl2DbZguK/GL+gcrg==,type:str]
domainFilters:
    - ENC[AES256_GCM,data:9I2Ga+OOI4NeWXMCG6cg,iv:9k2Zccs0LKuHxCIXrmT7jt5JNlNarqSY53Halo4X4rI=,tag:5BfTity9Akm+5tAIYpq4CA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTXIrd2pGTWhrREpUNFp4
            UGVBUFg5U3locWMzRWdWNjlxTjNWSi9VZHlFCithQys4RHB5WVJaWngrTlFINGFj
            WU9mQ1ZQTlpjWm9uSnI2YytUbE9MYVUKLS0tIGY2TldOeG9IV2crY3RDQXpyd1Fn
            YTZNY2E5ejYrMDlMVHo4aFlxelJTWVEKVYb72SlnUpHOZFiOCSWnhk6DVYTaEvXP
            8B+66YSkL82167nZvvt9tmWUd4f4lfcE25N2+f4cBgvBMzl88t1FXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-06-01T02:18:41Z"
    mac: ENC[AES256_GCM,data:VnJ83ykrteQN0Lq377acaAw3hj8bSP0JJDYDUVqelC1DfCjG+AaacnqSOAJkYDPKRW7dCxgbJ76AB89371YsO3zKB37rZkWssLZjAy6NEKakcfGxDS52FYs5LaEwScAX2i2IILLjPQlL3RvVPu5bI2qmwv9GHXAv05J93q2IsdE=,iv:IwIeMIEMkFQeBepcUcehUa27FivmM7C/fCAdRWYxG60=,tag:JcjWbzlo/nhwIbuwxd5MHQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
