UNIFI_API_KEY: ENC[AES256_GCM,data:mC4YOLy7rDNFEuiJGKBjibh3zApwlrP2EpEyk5JXDGk=,iv:/HbuyIvsXV2ikLfTtjbbQAhDzXuBWGcB/SxqHr8tw3o=,tag:V5LVGmqkk85KXN+lGbMypw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTXIrd2pGTWhrREpUNFp4
            UGVBUFg5U3locWMzRWdWNjlxTjNWSi9VZHlFCithQys4RHB5WVJaWngrTlFINGFj
            WU9mQ1ZQTlpjWm9uSnI2YytUbE9MYVUKLS0tIGY2TldOeG9IV2crY3RDQXpyd1Fn
            YTZNY2E5ejYrMDlMVHo4aFlxelJTWVEKVYb72SlnUpHOZFiOCSWnhk6DVYTaEvXP
            8B+66YSkL82167nZvvt9tmWUd4f4lfcE25N2+f4cBgvBMzl88t1FXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-06-01T03:23:53Z"
    mac: ENC[AES256_GCM,data:es7Ek6C+HBld9HsbUSFSLiSSER89Ri+iYIIqgGec2GQhgePYxEWJLCYR3kBFc/MuIg23pUee8nqzRw9fEOQpKCIxasJuc3gh0rgx4uQocvOkzInpac/HeqF7zuT9JPGNTWn9ZFT7lvvhEiAGizc/aD34IMNsRgW4rHzAZ/v3VgA=,iv:8zbdogzkiTZBnkMCeC5wE8FYv15FRBgava8haBaOHVk=,tag:UrccoRGtuvluuiFxvN/KWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
