ingress:
    main:
        enabled: ENC[AES256_GCM,data:gCX/WQ==,iv:oBgjsSCzNSedHrYhMDScP9LNAhmXI6COk6FqMdru22k=,tag:eOyvl2XOBamyovPq0itmTA==,type:bool]
        hosts:
            - host: ENC[AES256_GCM,data:6v5aEV/k/u+igqTKsnRG93naNcnW,iv:X73JXArRhAtEEHsCDlPonb0SKjG4oOtHrIWlM26wqeQ=,tag:GI99+ZFTfK/Iwn91jlqUSA==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:Mw==,iv:HpQK5uFnBsmQPmSI3t3Kn6bq61bK/I9UOKCx1U0ZGy0=,tag:r5pdMm2W1p09iOwwS5rHxw==,type:str]
            - host: ENC[AES256_GCM,data:Yqan2W5e4A+7Xp3nk2j9W9rdqSrF,iv:kB5FWujKEJWa6X+tPsj0u5OYaT923f1ScEe17Uaatng=,tag:vxd0KNo7XYNmwMhiPN/PIg==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:Mw==,iv:HpQK5uFnBsmQPmSI3t3Kn6bq61bK/I9UOKCx1U0ZGy0=,tag:r5pdMm2W1p09iOwwS5rHxw==,type:str]
        annotations:
            external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:pI6zFwGWRazctN4VsAArF0mOPP//shLq58WJGZVHjrAJ+yPVHwAUoiqwPg==,iv:oJ2Sb4cgKGrmtcyAv2+zUSBVKne4HW0nuYn6aibgZZw=,tag:IidBllnCmh7SAIwKsXcrQA==,type:str]
            external-dns.alpha.kubernetes.io/cloudflare-proxied: ENC[AES256_GCM,data:PtM+eA==,iv:jdviDB40RBVHZM8Wk1kxthS0DOJFeDROV0j/5DdhcGw=,tag:LTZFXDz02GN/M1YMPgQntQ==,type:str]
            external-dns.alpha.kubernetes.io/target: ENC[AES256_GCM,data:G9BO8bw4OdjFGKgg+86r/RBIM+sFboEznmIB0FMvEgYn2MQRcqSsxJMCkF6jBcToNE3x1WA=,iv:c8cafmFY8xduCkRyRIjuvQDvkvyc6pCLLLf2AoZNoOc=,tag:zmsdABOt6azwuQSSYg1XhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWngzeFRiVXVtVnVrOTJk
            ZUdKQWNYdGdkMU5YOGc1WVRYTDhRSis5MDFNCnE4RTUwQVQvQVlSSU9GNGhFZVJS
            NnFIQmxzZW4vRTJYRDlJMEttbU9DY3MKLS0tIE1tenFIdTdvYnNsekMwZFpiWS9n
            Rll5MnlqM3BUVkcxR3BUZnZ2RHFkd1kKJ+3dwhhRprfz1Fku/SBK2qX6Msflh/Tg
            QGpTyaiBKHVxLFU7OLLJDt4xiJjzBg+Ul//ZLhlU8qgxadtix/Oamw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-05-31T23:07:28Z"
    mac: ENC[AES256_GCM,data:oegnSCV+q1AfrKhXp9bm615pW5A58XVRkduLvPZ5dt5dNqIkOPPU2cICdBiqeJxusah+6SbIP8cR6CdBSg5eQJ9KbsmwPkIF0U4Ck9pqUp1U4yy5UwXaPJ5H3pBdctWthOXfwmcN4v5uB/ytYvKAFv4wdGg4jT39Kkye0a69WhY=,iv:8/bC7oYiNq+P4pwoe0m4j4kV0hQaRADLMrGYhh0eazo=,tag:ip1iZ2oH4q3+9B7ivPznxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
