ingress:
    main:
        enabled: ENC[AES256_GCM,data:gCX/WQ==,iv:oBgjsSCzNSedHrYhMDScP9LNAhmXI6COk6FqMdru22k=,tag:eOyvl2XOBamyovPq0itmTA==,type:bool]
        hosts:
            - host: ENC[AES256_GCM,data:6v5aEV/k/u+igqTKsnRG93naNcnW,iv:X73JXArRhAtEEHsCDlPonb0SKjG4oOtHrIWlM26wqeQ=,tag:GI99+ZFTfK/Iwn91jlqUSA==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:Mw==,iv:HpQK5uFnBsmQPmSI3t3Kn6bq61bK/I9UOKCx1U0ZGy0=,tag:r5pdMm2W1p09iOwwS5rHxw==,type:str]
            - host: ENC[AES256_GCM,data:Yqan2W5e4A+7Xp3nk2j9W9rdqSrF,iv:kB5FWujKEJWa6X+tPsj0u5OYaT923f1ScEe17Uaatng=,tag:vxd0KNo7XYNmwMhiPN/PIg==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:Mw==,iv:HpQK5uFnBsmQPmSI3t3Kn6bq61bK/I9UOKCx1U0ZGy0=,tag:r5pdMm2W1p09iOwwS5rHxw==,type:str]
        annotations:
            external-dns-cloudflare.alpha.kubernetes.io/enabled: ENC[AES256_GCM,data:pJ7U0w==,iv:/VN1mB6XA7fEoGi7sWokr9JRalgY5kiitf1TTHtuOf8=,tag:NRSz+SWw8XS2bjOgiyPtyw==,type:str]
            external-dns-cloudflare.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:mp46lY/gB00aBGkbBnaw1fxAMsywgqjLSqkkX3//iNAiAtIt61Zd/qnYcw==,iv:NJ5MCH2UKRM+TyM0h7da9NIQHiUXKOGir7Js9MwSydQ=,tag:4UUHQgrIo7ezIIIXZjaOpg==,type:str]
            external-dns-cloudflare.alpha.kubernetes.io/cloudflare-proxied: ENC[AES256_GCM,data:L5EcbQ==,iv:sN54AG2ec+mDgB+J2h5EWXk/6nyUlavo7v/Y1r2wb34=,tag:pPKPUOP8Rwmy9Jd4HCMsYQ==,type:str]
            external-dns-cloudflare.alpha.kubernetes.io/target: ENC[AES256_GCM,data:sXpYnHVf6f74So8pvaBmO7Jz/SfluPS88pdVT+Iml4nz7H7SHGKpuL5bXyjqHEoo9uEpv9I=,iv:IyOT5qQ0aTt25gyWEnO2MSAYNRnoIy+CKYQ9i7Z2+2k=,tag:QTcBYVl3nKrGdb8lYbgKzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWngzeFRiVXVtVnVrOTJk
            ZUdKQWNYdGdkMU5YOGc1WVRYTDhRSis5MDFNCnE4RTUwQVQvQVlSSU9GNGhFZVJS
            NnFIQmxzZW4vRTJYRDlJMEttbU9DY3MKLS0tIE1tenFIdTdvYnNsekMwZFpiWS9n
            Rll5MnlqM3BUVkcxR3BUZnZ2RHFkd1kKJ+3dwhhRprfz1Fku/SBK2qX6Msflh/Tg
            QGpTyaiBKHVxLFU7OLLJDt4xiJjzBg+Ul//ZLhlU8qgxadtix/Oamw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-06-01T04:34:05Z"
    mac: ENC[AES256_GCM,data:UdXp+djbjnNO8KKUiCiZeJ9ELrH+ItOqrN5/FK4lQBI4mhFMfu6cIms7ZWmQXWarRV1VvjEzrFqHZRQIdwbJ3+D+/5BmdSzU/sGOCqfto7kLv9zMiEBg5Gs6sKhfGXCnPEG6sP2HJgWQ7SiUNX2vLm2MlktrNUtxCeydSm9vTF0=,iv:MkqQroXGLpuYppW3CAdS2oFJkUK6hx6tU/07S4cZlx8=,tag:XvRAqxZ6md70+24KX7LcAA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
