repositories:
  - name: djjudas21
    url: https://djjudas21.github.io/charts/

releases:
  - name: homer
    namespace: homer
    chart: djjudas21/homer
    version: 8.1.15
    secrets:
      - secrets.yaml
