ingress:
    main:
        enabled: ENC[AES256_GCM,data:gCX/WQ==,iv:oBgjsSCzNSedHrYhMDScP9LNAhmXI6COk6FqMdru22k=,tag:eOyvl2XOBamyovPq0itmTA==,type:bool]
        hosts:
            - host: ENC[AES256_GCM,data:6v5aEV/k/u+igqTKsnRG93naNcnW,iv:X73JXArRhAtEEHsCDlPonb0SKjG4oOtHrIWlM26wqeQ=,tag:GI99+ZFTfK/Iwn91jlqUSA==,type:str]
              paths:
                - path: ENC[AES256_GCM,data:Mw==,iv:HpQK5uFnBsmQPmSI3t3Kn6bq61bK/I9UOKCx1U0ZGy0=,tag:r5pdMm2W1p09iOwwS5rHxw==,type:str]
        annotations:
            external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:MhXgw0fsaGP0GQE11Eic7L5wYDsRVA==,iv:6gu8JsbgKvh9odXKfBPVYXJP7PmZeJGYeRvihVTz0ow=,tag:CU58K2z/nEh/CGcLsaqLTg==,type:str]
            cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:McOUB2RVDkqJX2LlqQETNgLuwuvNjg==,iv:FCtt79M9M0+pMvX3vZ0GvHuuZJRlHiLqcgsaeLAN9S8=,tag:btF9W8uALdn7yQMpUvqASA==,type:str]
        tls:
            - secretName: ENC[AES256_GCM,data:UFm09QifGvYA,iv:c74exV4sV03JLW7aPk6nJJ5MmEUi6ZWrtfKqjD/TkU4=,tag:PL8dMail6C95LvfAGmHKJA==,type:str]
              hosts:
                - ENC[AES256_GCM,data:p9T8Hvwsl0+HzSaMFevplwKFvRZ6,iv:Zxr4pKM5vhyh0/SqVF6ko8HKBULBPEop1X+xIgiUrIA=,tag:Mb5B38zD4TZZ+Sn548ZoMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWngzeFRiVXVtVnVrOTJk
            ZUdKQWNYdGdkMU5YOGc1WVRYTDhRSis5MDFNCnE4RTUwQVQvQVlSSU9GNGhFZVJS
            NnFIQmxzZW4vRTJYRDlJMEttbU9DY3MKLS0tIE1tenFIdTdvYnNsekMwZFpiWS9n
            Rll5MnlqM3BUVkcxR3BUZnZ2RHFkd1kKJ+3dwhhRprfz1Fku/SBK2qX6Msflh/Tg
            QGpTyaiBKHVxLFU7OLLJDt4xiJjzBg+Ul//ZLhlU8qgxadtix/Oamw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T22:22:42Z"
    mac: ENC[AES256_GCM,data:/0jdJsL1Hv9gP3fJ0sXqmuuhiq6IK3xx0x2EqJp0mLwl/rlqIob0BmWXa0rWBnFPaQdewQZssxESkLD78imkHwOQY2+UuqaPW4R8Jo9DNNS5k7D89OZZ4dE3yzrFizfsDquEa99oSom9PiwU76gcwj18HxNkzr+F8PuxR/VpffM=,iv:KAbTCGZFS+woa/OfuBnrb8FonG9uXFNxl/TWi/VFQAo=,tag:8n07KxX2j2aqrjTJ7aJzqA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
