ingress:
    enabled: ENC[AES256_GCM,data:YhEtpA==,iv:9T9EXTSzyFTugR2uqNWMicwpfTwq7LRKT26pRL2OU5o=,tag:zgRTM4G+1phACpsKb3w+Jw==,type:bool]
    hosts:
        - host: ENC[AES256_GCM,data:bzrDN40ITH//PjHVfJA3QUP9Dt83y9XV,iv:YnFo/6uGGJEpaLjmbslLpAoWXcfM6ARsjbogmurAUy0=,tag:ZXISjIVh63ww3ONO/lIjmQ==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:mA==,iv:jZ5sGq1KwP4eMfG0en5m+oPYMBuuBw2Iw9iMUAkmwxY=,tag:sYOuKb3f0KbmQ7e7EJRftQ==,type:str]
              portName: ENC[AES256_GCM,data:5ZuC3w==,iv:unTCU4wTx+Y80FB4XFYx5zUf1eaNebbEAind7kInfeQ=,tag:JSttZUnsc6mqcvIzf6HdSw==,type:str]
              pathType: ENC[AES256_GCM,data:zEQklHI2,iv:O4LSnHFVxoxYu+mhfJvfJHbPFKkMqr+oMs7qpE536vY=,tag:2ytl4Dj8MGS5x0Iwz4G1/A==,type:str]
    annotations:
        external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:0wva7z6P+7OasVEPHLcX/dPLARLQ4CXTeQ==,iv:NnoITStqo7uwEQKUSBy7qOcMjum9cXQX9kxwIh2p6jw=,tag:cw9sBtiZmkwmjuvJjeT3vQ==,type:str]
        external-dns-cloudflare.alpha.kubernetes.io/enabled: ENC[AES256_GCM,data:tq/c3A==,iv:rIPs8KUltkP+2e7dDDLIhknbiynxDsBQMcRilBh00RE=,tag:uofW9DMj8O83tJJTPoFJjA==,type:str]
        external-dns-cloudflare.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:2tRHjzCePnnjrL7XT2rKbOBTXnKmnMwN,iv:JXKfDYCPECt/K1jFEJhzUXZvE7l1bSqPqtlOCOXFnqU=,tag:KZ8yVQOsga1sSKwIbLnc3A==,type:str]
        external-dns-cloudflare.alpha.kubernetes.io/target: ENC[AES256_GCM,data:gkyup9X7t3TvsAK6/6mheJf9GZZVNxf/JX8JzkcdxGnYF8NHxynnII0pPhjY3jM/E9e6/PM=,iv:p2fa7pkM4DpJKtj/ZIa4A4qYS2nB8jK4dNAHkV1txbM=,tag:TxyE8etMpk/TZNK2a0L9RQ==,type:str]
        external-dns-cloudflare.alpha.kubernetes.io/cloudflare-proxied: ENC[AES256_GCM,data:77v5ZQ==,iv:u6+E/LuZqa28i9LdI4n7cDN6QC0aR4qRYdPMLH0Tglo=,tag:Tk1J8j//Odxj72szycJraQ==,type:str]
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:da8Ukle0pB+J8nrJj3lvsM5EVuTHLQ==,iv:tqtvJK6tzH7AmlrNIb+5qSQggD5CrLiWBXLK6sZybEg=,tag:2iY7hw2iC0n1WbYhwXXupw==,type:str]
    tls:
        - secretName: ENC[AES256_GCM,data:zMtC8ecE4Ds44TnP,iv:Wt5ZxrsVM6iD0T53v4xwaMgffbzZqk+rYB+FX3CDt3s=,tag:40u80zFftCu2dLGUKsfT8g==,type:str]
          hosts:
            - ENC[AES256_GCM,data:cV08qIjESkOhWI2ua5tgzzZgisuRdi/c,iv:GjbE2t2yURvbqffr8ypG0Wdv+LG7Pf5uDPqFllP+O1s=,tag:mXZMwrmpdwIAkGMIOgM9ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdkdKeGdiWGowa1J4Qlh2
            OXBjenVvYVByaWFGVkt1YVltOXJ4MStGWFI4ClhlL2NScDdpeDlYNGF0SlpHZTdr
            V1dIMGJqdXlCMWl5djJrN3RYeGNsQWcKLS0tIE1GUGVJT3dWcGZHeW5VbXpIU3Np
            dGtoTUtvTGtNMHd6LzVtMnlDRlJKUjgKNmWuksYUqbAS/BPz3OqVOcHQxcRsmazC
            /p6JykRZ7alSjdX1yY0rgkefG5MHrZIQIHYw8PWTGy+UU6/Dj1VvIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-07-19T22:41:45Z"
    mac: ENC[AES256_GCM,data:EKFW2IQ4wnpHD8NC3gk8kXUHEAUYPjBu83v0S9QBdt7kdoMzitgCm3SokNKhcGPf5nwHF5jX9LntbdVp0X3LgllRDPCn4jVdOTmEhxSrM976V+22wnwyai7fXT5S0qNPmMZJuH9N/F6rAE/2gVvvQcoomPJBg1asgWOwnm9mwpk=,iv:xAsr+vu72z+scTa9apyQgAVmkgBvI4awIgnjswRYm40=,tag:bLql4qaztEkFUz+oyRyRgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
