ingress:
    enabled: ENC[AES256_GCM,data:YhEtpA==,iv:9T9EXTSzyFTugR2uqNWMicwpfTwq7LRKT26pRL2OU5o=,tag:zgRTM4G+1phACpsKb3w+Jw==,type:bool]
    hosts:
        - host: ENC[AES256_GCM,data:bzrDN40ITH//PjHVfJA3QUP9Dt83y9XV,iv:YnFo/6uGGJEpaLjmbslLpAoWXcfM6ARsjbogmurAUy0=,tag:ZXISjIVh63ww3ONO/lIjmQ==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:mA==,iv:jZ5sGq1KwP4eMfG0en5m+oPYMBuuBw2Iw9iMUAkmwxY=,tag:sYOuKb3f0KbmQ7e7EJRftQ==,type:str]
              portName: ENC[AES256_GCM,data:5ZuC3w==,iv:unTCU4wTx+Y80FB4XFYx5zUf1eaNebbEAind7kInfeQ=,tag:JSttZUnsc6mqcvIzf6HdSw==,type:str]
              pathType: ENC[AES256_GCM,data:zEQklHI2,iv:O4LSnHFVxoxYu+mhfJvfJHbPFKkMqr+oMs7qpE536vY=,tag:2ytl4Dj8MGS5x0Iwz4G1/A==,type:str]
    annotations:
        external-dns.kubernetes.io/hostname: ENC[AES256_GCM,data:5RuNl0l4UGbtpAlOdBHO0Y1FGYuD4psY8A==,iv:obnmMu+8/SNDCAvmZW5vElv5F+DxjhiH89RTzEFMpnQ=,tag:XZG8Noc8q79rq/yWUIUxcA==,type:str]
        external-dns-cloudflare.kubernetes.io/enabled: ENC[AES256_GCM,data:wxQx2A==,iv:dw2welmEjXQYCgioHyH0GjlWMRyFQ4tAjGu3puCZ0S4=,tag:kB6c7WUFUlJ+ujzaZpF7Zg==,type:str]
        external-dns-cloudflare.kubernetes.io/hostname: ENC[AES256_GCM,data:AEvaboGa9Hs3GBEXnuldb2zehsFGx8jj,iv:YMcAcr68v1hZN3bWiwhWJeAVmQ+amk9BNJ6ywulA8d8=,tag:MKLlRjnPNdSU2+F2+Krhpg==,type:str]
        external-dns-cloudflare.kubernetes.io/target: ENC[AES256_GCM,data:EILRAcQByxQoMYuvrxfwpixUAGP6VM/b0sgHqTOsVaQMKq6x1eyxoGO9SC1s0h5QcNTFSfQ=,iv:RYJEINuGLZL2Vw3Ns3bVuQJ1tiTC+sPBaG8LhHgFQTk=,tag:geBaoyW0Nm/2Po3yETS5UQ==,type:str]
        external-dns-cloudflare.kubernetes.io/cloudflare-proxied: ENC[AES256_GCM,data:jkV1bw==,iv:Q0CElE3xR4yNet5hrNykUAa5RFS1JPOqKcrK39R4k18=,tag:ADkMjdvbB9N5Qac1J00rvA==,type:str]
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:da8Ukle0pB+J8nrJj3lvsM5EVuTHLQ==,iv:tqtvJK6tzH7AmlrNIb+5qSQggD5CrLiWBXLK6sZybEg=,tag:2iY7hw2iC0n1WbYhwXXupw==,type:str]
    tls:
        - secretName: ENC[AES256_GCM,data:zMtC8ecE4Ds44TnP,iv:Wt5ZxrsVM6iD0T53v4xwaMgffbzZqk+rYB+FX3CDt3s=,tag:40u80zFftCu2dLGUKsfT8g==,type:str]
          hosts:
            - ENC[AES256_GCM,data:cV08qIjESkOhWI2ua5tgzzZgisuRdi/c,iv:GjbE2t2yURvbqffr8ypG0Wdv+LG7Pf5uDPqFllP+O1s=,tag:mXZMwrmpdwIAkGMIOgM9ig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdkdKeGdiWGowa1J4Qlh2
            OXBjenVvYVByaWFGVkt1YVltOXJ4MStGWFI4ClhlL2NScDdpeDlYNGF0SlpHZTdr
            V1dIMGJqdXlCMWl5djJrN3RYeGNsQWcKLS0tIE1GUGVJT3dWcGZHeW5VbXpIU3Np
            dGtoTUtvTGtNMHd6LzVtMnlDRlJKUjgKNmWuksYUqbAS/BPz3OqVOcHQxcRsmazC
            /p6JykRZ7alSjdX1yY0rgkefG5MHrZIQIHYw8PWTGy+UU6/Dj1VvIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-09-12T18:33:27Z"
    mac: ENC[AES256_GCM,data:7bFXOVNL9d+vc88Y/44xhddUJG4wd7OU3JhEI1bUcKgTUuZQdvUnyWDdwjwOA6DrH4fRmO60gm3pj4EdPV1ihjLXZMOvUmNCYQwunNrsuD/Nu4/uzQI0/ZOSRE48EKEqM7/3NbN47lAtr9pWqSQO9+qXq1g5j4zhrcw73N4pzpo=,iv:2Iqqw/jMyiSe2Dr4USaXc8PsW6cEpslUZmje/9t2DcU=,tag:GPNIkqUJAmb3z6D9vAAuyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
