ingress:
    enabled: ENC[AES256_GCM,data:sAHZgw==,iv:BudhkaGZO8Q3HV6iBhf6Ry5Tsb70VXFudmzaQwWa8dA=,tag:Tuqg2uoLazYqJ6HT7BmbEw==,type:bool]
    hosts:
        - host: ENC[AES256_GCM,data:Surv5zVNoqv6Vc1HiQWTUi143nW/FfNb,iv:o+uvPLn8aqEBzCyLJxRaZ8H2Hi64C7PmT0B7aneSoBE=,tag:RStN806TAQbdXoerjurPdg==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:Ow==,iv:4wFa3ZhDHBvy2WpnahXeqef2iRdkpCsGGPhjxdmHgeY=,tag:VpEaBiamw5SRIbw7l85sDw==,type:str]
              portName: ENC[AES256_GCM,data:oV0x0g==,iv:EcxCreob+2FUV4wc5+ywGYGxRTo6FfTVQyyuRuRAXIo=,tag:ksyF0xovYTk0mxgx4/sbIQ==,type:str]
              pathType: ENC[AES256_GCM,data:pIXq09IX,iv:2aZpdYe7OdW8Vws5fFHERealWgmYf/Oe8csSC4pbekk=,tag:nTwS574axMEI2TDglok7zA==,type:str]
    annotations:
        external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:+RXsfl05XktYhvFnJQDrsgk58Nn8jHtIQg==,iv:JVtTR2Dfd2BQDs+kki75weKtNKhWxQ75NoewLjS/f64=,tag:ex/ZCW4yzje7r3oB8AYrtA==,type:str]
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:DQKhKOpIj4uFXjG5yAl1LpYnwVgmhQ==,iv:FT/X5b9Idw8aMI94hymr2sAYnIOBIyxLDzbSgHWu6Lo=,tag:ssBiEIczWc4hKZaMZeyBBw==,type:str]
    tls:
        - secretName: ENC[AES256_GCM,data:yz2NvaT0kmjJdi1a,iv:Ky6lwTUyZCAHpdsuqtafJ1iCX2MaV3LwbM55J5uAipU=,tag:U8o2Do5mfuBy2Ju3noeUCw==,type:str]
          hosts:
            - ENC[AES256_GCM,data:R3McZiwy/Zr3qRXp4A+vYkzgZx1CbcWP,iv:o6RCVb2EHW5cARxtqPBPnm0b2LcBuDRfmjZN7ihX8t4=,tag:eEXXDKlDvT6mFMGyPNa8IA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHS1I5NE1UUlpLRUd3UldR
            Um5IUkFXcnNIY1dEQ3RXYTBEMGtDQnY3V2pZCm43cjJUVGVOTHUvdzFGS2NKZVFw
            V25ZL2dHMnJOV0lvTkx4WFdWNk1VZ0EKLS0tIHluaXFCaEErVDJYdVR0N2RKVjlv
            OC9NQkI3SmFZSDQraDYwVnQvendVL0EKlrX3s0tFnOUgk7kcAgc0FIT+gygYd9dg
            a0dn9wBnUlEA2lft+VwX6T8pXSP6fD7o7DLTLyXBUB4ZiPFKnMlGYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-06-23T05:17:13Z"
    mac: ENC[AES256_GCM,data:tqyY1GcQ0tD+BwFgNLP1GFeLd/ChZI6uLKqas33m46La/0IUFCuLsyZLoe6f1XorMIsOQlW7WAnYVEkmqyIvpUv5huSsJ3KWdRLx38XpxOz50jD54g33Ok6jEvbd8GRA4ZluVvy6cJz7p4PhmHJWyuxt/9g2b7yBN5xsIqcFK9M=,iv:fSvbQH7UabsUQqV3v9T6F4pYw4opkHoHRFQdvdpwG4o=,tag:5JmiDcxtupaYeTbkbFzNAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
