commonLabels:
  sync-stage: system

repositories:
  - name: metrics-server
    url: https://kubernetes-sigs.github.io/metrics-server/

releases:
  - name: metrics-server
    namespace: kube-system
    chart: metrics-server/metrics-server
    version: 3.13.0
    values:
      - values.yaml
