repositories:
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
  - name: otel-collector
    namespace: otel
    chart: open-telemetry/opentelemetry-collector
    version: 0.102.0
    values:
      - values/otel-collector/values.yaml

  - name: otel-collector-cluster
    namespace: otel
    chart: open-telemetry/opentelemetry-collector
    version: 0.102.0
    values:
      - values/otel-collector-cluster/values.yaml
