repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: loki
    namespace: loki
    chart: grafana/loki
    version: 6.7.2
    values:
      - values.yaml
