commonLabels:
  sync-stage: system

repositories:
  - name: intel
    url: https://intel.github.io/helm-charts/

releases:
  - name: dp-gpu-plugin
    namespace: inteldeviceplugins-system
    chart: intel/intel-device-plugins-gpu
    version: 0.34.0
    set:
      - name: nodeFeatureRule
        value: true
