CF_API_TOKEN: ENC[AES256_GCM,data:DQniSQVxnuYkez8JVZGebMd3STrr7cTKi0M4/0iw5ovWABGbjzdE8A==,iv:KxAUEaCrrNRBBkQ4iLlnCatDNGjpoZdAUdaQnMQ+F7c=,tag:rXyKUyN2XiEiccyg/BQMBA==,type:str]
letsencrypt:
    email: ENC[AES256_GCM,data:IgUZuAbU3B+gWmJDtzxpDu0GQA==,iv:tn+w51oQbXIEWYHmNUlh0YovB52kRr/Aq6LilPWjBdo=,tag:2uBFSh+bwoAyz8WSqtpYyg==,type:str]
    dnsZones:
        - ENC[AES256_GCM,data:qOZVwzGQIHgMhNAGujDt,iv:lTQcGH3nNgbwZ+t9yJ9ORq7n21FRtO+v7gyK1e3xgdQ=,tag:W/i59c2CkjlHjSwOFrsohA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTkluVmNHTzJrTldBWjRr
            VzNBREtvaDJldExldHhxR3g5T0MzbVBicENNCnNHMzlVeTJBL1FKL3RHZWMvTVNy
            Zm1vbElCaW1hYWQ2VHI4THZZSTIxeUkKLS0tIEZnWVVUUnhTbjR4T2FJbEdkNjRw
            eTNSQ0lMSXVBZEp1WXoreElYRktsdzQKN4zi3xR8OAG58S+SW3KricDKa9pMGS8d
            15/RzwOPHr0eRVCx47KNrICEWnKlG5CZWLhTj9zPIG1oK3zsh7P+/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-06-01T01:53:58Z"
    mac: ENC[AES256_GCM,data:tWQffEM3/EUMzV/7lI4DA0PKfW2M1PTz5nxPPC95LEW+qf9rbOta0MVAXYi5iDnk0Y1SmaIkH7HiBQqBYpKXZiwn8IPgSC8GOlQrDLG9os12BiniuwzCltvjyjE0sLu0/Y33seRsX8GJzqmyuPDzQe5akmKb8Lfc5EEvrGIVpgU=,iv:PQ6Gx8XjDH6mjSdmTr7u7DkZfhOHyOXqopqwc7K+rsk=,tag:HnQyFDzWj+1CBhamLe3iJg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
