commonLabels:
  sync-stage: apps

repositories:
  - name: mqtt
    url: git+https://github.com/halkeye-helm-charts/mosquitto.git@/

releases:
  - name: mqtt
    namespace: mqtt
    chart: mqtt/mosquitto
    version: 0.2.0
