peers:
    - ID: ENC[AES256_GCM,data:EmiyjtNfUNC9q35EWbfKNYx9ofAG1lqZaRO+BxeKvNZova9xErybF81U6TW5s5fAJFMw64m3Rn3YGAURz6nu,iv:1Yh2qCSX/a5uWXiuIYKgCtNozMEVpqyWZm85VeKEPTE=,tag:i+82RJJDWeNZyaWm9PeYUA==,type:str]
      address: ENC[AES256_GCM,data:Vr2vNaFSV5/uzfmCE+QHoDdSuVlLv3WJ9Lvku1e9jg==,iv:vsJrVOJzvWlnBVQ3HJo7o5akdQb/PILaAGfOc1lualE=,tag:BFkOIqtBTLpFpGZiRTXUXA==,type:str]
      introducer: ENC[AES256_GCM,data:i/Q59LY=,iv:01aH5rt4rc2Wrh3o4ToK8sV6tvc1uBdqRNSjSnAe9pE=,tag:8qRGzgQiIzzvjb3yi2Flbg==,type:bool]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUnVpZG9Yd1VvWU43a0Jt
            MlQyOS8xQXc2SzdLQ0xKTTAyOUZyRSt0aHk4CllVQUk3T2dHKzJWWk5Id2U4QVB3
            bVQ5YlR1cjlzdE80MlNNWUxWQ0g2SUEKLS0tIGgzUHdGSzhWS3VDdEVHcW9pTGhD
            cHJkRGY5bFMvdlUyWVNlSEdZMFhTZWMKM2RGOS1eU/gF9TC+QGIoJuNjm4301Xcv
            0DhPBG13vxBrsO8afIo6+yr9rxVC6n7KaBr3loNm3UGH+3pjA26U0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-07-04T15:39:07Z"
    mac: ENC[AES256_GCM,data:d+OsUOqZXHI7WXEcyj+hBqx4h2hSUCfsHFxPzlYDRkxQH8OKRosa5SjnMdsmtv/lmvzb7hmJPL5GWK4psDY+3bSLMDM2R7OxJe63+eyJoYT7AzH0pYxt96VF/R2MtjRZmJDw1efoLYb/hlreTC6pTcx8JbBhe20tL6efRY40AQM=,iv:MBc0lM4wSTo/PO1U3mmsjCj96lehyjfSOPUW4un+OzM=,tag:KmDmJyCq82+/VgujepnlFQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
