ingress:
    hosts:
        - host: ENC[AES256_GCM,data:vdqiyfndaGqylD0RgFyvhVpPfTU6t59NmQ==,iv:AV6Wju6u8Dd8MhEYwqwanWU7bZTZ8CjFCG26k/tdkOk=,tag:p/gNCWxg+kpfUjOh+NtaSQ==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:dQ==,iv:XfdEcstDtUy0YUJoNjuwdgQ3PVnpLrZTVJIeGSbSJ0c=,tag:mHVbArv5mP8WGTM/RCxzvQ==,type:str]
              pathType: ENC[AES256_GCM,data:LyhPwfW3Bumk5NkTm/phVNyYXzEofw==,iv:RJhcpPr739eZVtD2UOqrdA5VVEL/rs/YMAnDzdKLKvs=,tag:O0+mihBktoRILTVD6jsYKQ==,type:str]
    annotations:
        external-dns.kubernetes.io/hostname: ENC[AES256_GCM,data:s+BVV/NIqwxGOAwUmQjYGOmHTUCuuzBIpNU=,iv:A59SBtL8YRVaFQ+sq9C6iCvwICg+YB5dKlgTQ9jpEUs=,tag:9Ca2J93wphzTvVu0oiNnnQ==,type:str]
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:fpHJNO085/ccUW3UkNfBMYQSF628kw==,iv:tDRj6bFl/Db1DbV+2iTsm6Kq2G73ii04Nb9ye2tsmIQ=,tag:g3Lhwlr0dBqr88K8iRVS4w==,type:str]
    tls:
        - secretName: ENC[AES256_GCM,data:cpPlgUeYkiyzISlfVg==,iv:81jx4DDHMhwhMYKR7KFzkBdiztD1fhCH0V64OraNNKE=,tag:rbbAZPmcIXH4Ej9yw+pb8w==,type:str]
          hosts:
            - ENC[AES256_GCM,data:Bi8C9X9y17InU6yWoG9kOy1NJttqEBLMZQ==,iv:kKXmC/HoY8dnxxSgMcFFHg1XmgVCNbcHSXX2k0Ri0tE=,tag:RRwb9Wl9tsRLrQGJTyoNCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT0Q2YnF0WnJVZTdlN1hk
            M0I3RStzYXZwWWNka20vcGNmejhlNUUwSzBnClZielFPeHpoUGt5dUJwNUVrK1hX
            bmxWSytlWDI0U1NqQ1JlNjl2RDk4bzAKLS0tIE5RSXhKWVprZWtDeGdJRzA5ZkRt
            aEd6UDh4S3NqUHN5NFZOVXNLUUtFeVEKxTgYbyeikLqDMku73iESMDl8WvcF/iMp
            HoINgRoUESDO5aeG5nYlSWn1JS9I/lM3mCATzpvhbpv7PmGZWQOrEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-09-12T18:27:16Z"
    mac: ENC[AES256_GCM,data:/x8aaohOnydQ/iXxVy0NxNVIXzhPZCEB0VJnqEdEQiFY/LOfP6+ffFHiLytNiQyRP+W3+CzqPXzYYCQvKuFtzBJYeHbdfhkagxdFbMGAGrKSTurWWPlaD4sT4Ream73VHgIjptS+MFoXs0fQfZohH/ZBUcPOiuSTM28G/uleJUI=,iv:mvpVG1cOjN9QeRDAO8Sgtg0xM3XPQXCy0TwsvoHuQ2g=,tag:+e43jiOXJlkXoVyw6PTpqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
