ingress:
    hosts:
        - host: ENC[AES256_GCM,data:vdqiyfndaGqylD0RgFyvhVpPfTU6t59NmQ==,iv:AV6Wju6u8Dd8MhEYwqwanWU7bZTZ8CjFCG26k/tdkOk=,tag:p/gNCWxg+kpfUjOh+NtaSQ==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:dQ==,iv:XfdEcstDtUy0YUJoNjuwdgQ3PVnpLrZTVJIeGSbSJ0c=,tag:mHVbArv5mP8WGTM/RCxzvQ==,type:str]
              pathType: ENC[AES256_GCM,data:LyhPwfW3Bumk5NkTm/phVNyYXzEofw==,iv:RJhcpPr739eZVtD2UOqrdA5VVEL/rs/YMAnDzdKLKvs=,tag:O0+mihBktoRILTVD6jsYKQ==,type:str]
    annotations:
        external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:qKQCuCCaPfFPkhyH3zD/oIH7ZlVx77v42VU=,iv:mibwhSwSpnjNgZS0RadwmJqsJlBifa6mzMhhsIo+b58=,tag:Ci5Y7X1r55wHrK3opr7jgw==,type:str]
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:fpHJNO085/ccUW3UkNfBMYQSF628kw==,iv:tDRj6bFl/Db1DbV+2iTsm6Kq2G73ii04Nb9ye2tsmIQ=,tag:g3Lhwlr0dBqr88K8iRVS4w==,type:str]
    tls:
        - secretName: ENC[AES256_GCM,data:cpPlgUeYkiyzISlfVg==,iv:81jx4DDHMhwhMYKR7KFzkBdiztD1fhCH0V64OraNNKE=,tag:rbbAZPmcIXH4Ej9yw+pb8w==,type:str]
          hosts:
            - ENC[AES256_GCM,data:Bi8C9X9y17InU6yWoG9kOy1NJttqEBLMZQ==,iv:kKXmC/HoY8dnxxSgMcFFHg1XmgVCNbcHSXX2k0Ri0tE=,tag:RRwb9Wl9tsRLrQGJTyoNCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT0Q2YnF0WnJVZTdlN1hk
            M0I3RStzYXZwWWNka20vcGNmejhlNUUwSzBnClZielFPeHpoUGt5dUJwNUVrK1hX
            bmxWSytlWDI0U1NqQ1JlNjl2RDk4bzAKLS0tIE5RSXhKWVprZWtDeGdJRzA5ZkRt
            aEd6UDh4S3NqUHN5NFZOVXNLUUtFeVEKxTgYbyeikLqDMku73iESMDl8WvcF/iMp
            HoINgRoUESDO5aeG5nYlSWn1JS9I/lM3mCATzpvhbpv7PmGZWQOrEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-09T02:58:06Z"
    mac: ENC[AES256_GCM,data:KdL41ayzSU1oLZUQhPE7XL4WaKImAaj8oys4g8N69diWOAxCF53fJD/UzB9KIjgMvTyuUUffyxXAV33eeVk8wgx1zchksYWsv0qvdqxv3tg2B2xuhTOsPoX7EVEpmavR2NV/R9tK2VKpiA3ytjGXkBV2hOPZ84BSi1Pz+kvGJ6o=,iv:O3QCIOMMRu61kMxwMS7vyKhDOXLtJyLuZ/HqHfXL5tM=,tag:B5n/xoI3LB8C69fZCKlMHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.3
