commonLabels:
  sync-stage: observability

repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana
    namespace: grafana
    chart: grafana/grafana
    version: 8.11.3
    values:
      - values.yaml
    secrets:
      - secrets.yaml
