apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frigate-tailscale
spec:
  defaultBackend:
    service:
      name: frigate
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - frigate
