commonLabels:
  sync-stage: system

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.18.2
    values:
      - values.yaml

  - name: cert-manager-csi-driver
    namespace: cert-manager
    chart: jetstack/cert-manager-csi-driver
    version: v0.11.0
