commonLabels:
  sync-stage: observability

repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana-k8s-monitoring
    namespace: grafana-cloud
    chart: grafana/k8s-monitoring
    version: 3.2.2
    secrets:
      - secrets.yaml
    timeout: 300
    # passes --disable-validation to helm 3 diff plugin, this requires diff plugin >= 3.1.2
    # It may be helpful to deploy charts with helm api v1 CRDS
    # https://github.com/roboll/helmfile/pull/1373
    disableValidation: true
    # passes --disable-validation to helm 3 diff plugin, this requires diff plugin >= 3.1.2
    # It is useful when any release contains custom resources for CRDs that is not yet installed onto the cluster.
    # https://github.com/roboll/helmfile/pull/1618
    disableValidationOnInstall: true
    # passes --disable-openapi-validation to helm 3 diff plugin, this requires diff plugin >= 3.1.2
    # It may be helpful to deploy charts with helm api v1 CRDS
    # https://github.com/roboll/helmfile/pull/1373
    disableOpenAPIValidation: true
