commonLabels:
  sync-stage: observability

repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: grafana-k8s-monitoring
    namespace: grafana-cloud
    chart: grafana/k8s-monitoring
    version: 3.5.0
    secrets:
      - secrets.yaml
    timeout: 300
    # "Trick" helm into thinking the CRDs are already installed for diffs
    apiVersions:
      - collectors.grafana.com/v1alpha1/Alloy
