ingress:
    #ENC[AES256_GCM,data:aoSazEPjQR9v+m8eoGAxIf7bFwm6rpBabfnzKGDD4Jynj7cLdvff+U1N3dAtmVrQNQ==,iv:kIigZ+tcrV99SjOJKKbOf/R4YAsczmXz9IKtLywB8Ms=,tag:ICbb6DuQ+RtHiuOlDGQKPA==,type:comment]
    enabled: ENC[AES256_GCM,data:TJazOA==,iv:6IkjharO5M70Lo6IBCPf3n+tZieVe+W/fd6eeUnLxFY=,tag:FnI2ZS8ZX8eRX9u/mK24aw==,type:bool]
    host: ENC[AES256_GCM,data:QHhpNCdIjddXlSDDRAKBp4/ZeSAL+4pM,iv:aogJyhtlv0ezz+UNjkRGZwFo7Mj85AJfQ8D67UBeOqg=,tag:92ZOgvtvbiwnQAxYPpeasw==,type:str]
    tls: ENC[AES256_GCM,data:nogOeQ==,iv:wujZHgiH7ZFkv/TmhLoeRlPzCBMCD/tkgQ3sg0JPIgU=,tag:ExdcMthTt3KOV96ge3rHUQ==,type:bool]
    tlsSecret: ENC[AES256_GCM,data:OiSwx9Axyfq89ZY5,iv:R9FdSwjzzNc+PFNw95ere6X+XcgI2lPB93MiaCJSUjY=,tag:bgciVUo5ihiYGisQlVWIoA==,type:str]
    annotations:
        external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:JUapkrfdmBBAuGi7Rh/0vvGq57q4GGDCvg==,iv:Z22FyCcEfKehAByEPI+Z/xoIaYRm9sEf0L5t/jokkVo=,tag:d49b2uZ19QKsBoz2hOKeDg==,type:str]
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:Hau4rDGojsjVpSQWgJLyvrPFnaFh0A==,iv:WaVFVV3P2Vmi1JDiJab8/1gGow11eX6zUFRi/Wl8MRY=,tag:RWJaUhB36dUiLqxkQ2w/iA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWDVoMW9yUjd5TnpGYkRX
            NGNyWUt6bzVMMTZYVG5Dc0E2K2lDWUk1QkZVCk5JM2syZUtGdzJySURJbDQyMFFI
            Z2YyaXAyNGcvYTYweXpIQVhNSHBTRjgKLS0tIEVydTJRYWlQeGo1eW1aM2lRVHI1
            bHBPOUd1a29remtEWm5NREI1eFZRbnMK6ocri3f4l7czhO07Zm5mZ1MkTrLLxPFw
            o3hlvRYDO97XprQ08zjHimvXg/i4/ndHZSRWP/oME46xz3O4i+7/mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-23T01:37:06Z"
    mac: ENC[AES256_GCM,data:3C5dQMKvwoP8JKqdoOWq9v0im4IWY2c0ONid5B4Ne/E6U6xLQv69oC8uxfP7n3nZRhg/32BZGUWZS8+zj2Ksl6oAv1AlnkiMPaYRz2bDnCRCtPZHaGnTZQ5iCl/LkRloh134RJTwBETDmRZnT+K26eo/TcmzaU7LDxJ2JtsjwJM=,iv:r19eMn9irpD4lY9qUn1vNxnpbZjday5b/p1oCxiUQvk=,tag:MWmq+maYzBc5FsaxA5KIlw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
