ingress:
    #ENC[AES256_GCM,data:aoSazEPjQR9v+m8eoGAxIf7bFwm6rpBabfnzKGDD4Jynj7cLdvff+U1N3dAtmVrQNQ==,iv:kIigZ+tcrV99SjOJKKbOf/R4YAsczmXz9IKtLywB8Ms=,tag:ICbb6DuQ+RtHiuOlDGQKPA==,type:comment]
    enabled: ENC[AES256_GCM,data:TJazOA==,iv:6IkjharO5M70Lo6IBCPf3n+tZieVe+W/fd6eeUnLxFY=,tag:FnI2ZS8ZX8eRX9u/mK24aw==,type:bool]
    host: ENC[AES256_GCM,data:QHhpNCdIjddXlSDDRAKBp4/ZeSAL+4pM,iv:aogJyhtlv0ezz+UNjkRGZwFo7Mj85AJfQ8D67UBeOqg=,tag:92ZOgvtvbiwnQAxYPpeasw==,type:str]
    tls: ENC[AES256_GCM,data:nogOeQ==,iv:wujZHgiH7ZFkv/TmhLoeRlPzCBMCD/tkgQ3sg0JPIgU=,tag:ExdcMthTt3KOV96ge3rHUQ==,type:bool]
    tlsSecret: ENC[AES256_GCM,data:OiSwx9Axyfq89ZY5,iv:R9FdSwjzzNc+PFNw95ere6X+XcgI2lPB93MiaCJSUjY=,tag:bgciVUo5ihiYGisQlVWIoA==,type:str]
    annotations:
        external-dns.kubernetes.io/hostname: ENC[AES256_GCM,data:od7mkbujzmV3jZ9pz/VNEElT6OQYwZdT0Q==,iv:HIPfqExt01TPQfkSY6wNkJzJgc0HnrKIxndZIQMEdTY=,tag:PcbFwJHwdMqh/D6MpkzOLw==,type:str]
        cert-manager.io/cluster-issuer: ENC[AES256_GCM,data:Hau4rDGojsjVpSQWgJLyvrPFnaFh0A==,iv:WaVFVV3P2Vmi1JDiJab8/1gGow11eX6zUFRi/Wl8MRY=,tag:RWJaUhB36dUiLqxkQ2w/iA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWDVoMW9yUjd5TnpGYkRX
            NGNyWUt6bzVMMTZYVG5Dc0E2K2lDWUk1QkZVCk5JM2syZUtGdzJySURJbDQyMFFI
            Z2YyaXAyNGcvYTYweXpIQVhNSHBTRjgKLS0tIEVydTJRYWlQeGo1eW1aM2lRVHI1
            bHBPOUd1a29remtEWm5NREI1eFZRbnMK6ocri3f4l7czhO07Zm5mZ1MkTrLLxPFw
            o3hlvRYDO97XprQ08zjHimvXg/i4/ndHZSRWP/oME46xz3O4i+7/mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
    lastmodified: "2026-09-12T18:28:59Z"
    mac: ENC[AES256_GCM,data:8tEG7TJhSD9SewduxxF7gDF229lcohAxED3gUhJBALSqIRTprD5a+ar0X5g1Gq8/U52IjbTq0+NOGou2qYV1MpbSS6x1D0v9quHj0GMkqA3cJEc2Cax0keNa7lJvtZbYyCn/AoXwHvybRLWmNmOG8JYI9aoDsjFjjyofuAglLQM=,iv:E/8r9LolZ4X3Sc1NMLS9a8T9ctdxa/sKA4mfpfKaSLI=,tag:vebyckh4VgXA6eR1YNW9BA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
