commonLabels:
  sync-stage: apps
repositories:
- name: mariadb-operator
  url: https://helm.mariadb.com/mariadb-operator
releases:
- name: mariadb-operator
  namespace: mariadb
  chart: mariadb-operator/mariadb-operator
  version: 25.10.4
  values:
  - values.yaml
