service:
    annotations:
        external-dns.alpha.kubernetes.io/hostname: ENC[AES256_GCM,data:SajSEqjp3gJgcYGnpOOEvEcofLZSifMqsZKz,iv:aW2hy9SN0ptaar5XQcWGqCGI370se8juoDs71pwiCvg=,tag:+hnrMDS2S1ZlMaihZ4+DEA==,type:str]
ingressRoute:
    dashboard:
        enabled: ENC[AES256_GCM,data:vYhy4A==,iv:2Qb6EH8U9Z/iS6ApaNpO2j6+8gVkEjJL+FZrWUbvImg=,tag:IwLzOcVyLJnNZxz6tDmYYg==,type:bool]
        matchRule: ENC[AES256_GCM,data:y0UEGBZYMHSfBlGr5sduSGzbuKHKPmtLuvCXK+GOMgjWmKo=,iv:cyfg3XY8gMJfv+AmHdkPe1Ieu2eTwHN4MbwleHJpaKQ=,tag:yX4/Ftlig9usPeeqqJguSQ==,type:str]
        entryPoints:
            - ENC[AES256_GCM,data:3vZI,iv:0fcwidkIi9n35DHf7OkWbtmsLDDHXHDel7DqJvu3Aeg=,tag:r7iynoN0qV6YJEnTNdwpKw==,type:str]
sops:
    age:
        - recipient: age1g5kshkr8p50u034874ca4qsr60d29jcgnwaev0dm3fw6488xcfsqclpjek
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdDdaeVhMVGpPSTlyM1d2
            N2drTDA3SWZSM2tuR2JsSWZBVCtUNXR5MEd3ClRzUnA4OVBSQnBGNWZFSHhMd0dO
            dmdITFVQQUZIajZ0ZGM2QkVjTDFXQU0KLS0tIGp6U09kRHhremZlSUk5VWg0U3lQ
            clBBRnd6NlJodGJmVFhSUG91b0pubm8KJ5mxtzF5Wa54VMzFBvtWH5yOSLj94nEe
            XI8+3eEPXG4kY0wcyBv5nVi/saTkKWBLx0Km1G6irKtGuV1aMDLlfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T02:44:06Z"
    mac: ENC[AES256_GCM,data:wRJhW1EFHFxY2x9w62VCa0wJGKFatU1MRHxJRKeP1N4inbVFZkH6KegypdQjYm40SPkfdggagxSSfaPuknpOtqzedCNmzr2oHEYyYL0jvnxxTsYX9FVsgtuh5DZtHH3+K8iAHbyjqLHJWnQYStXSIkffqepKN/l0NOtuZ//Z0HE=,iv:1nTsyqPxxjsLea5D31jBRBk1a5/HTbOtGCwkUI2WX64=,tag:cduz0PX3LOwRmeAnnDnyiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
