name: Renovate
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.3
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
